## **Obtaining News Data**

In [87]:
import requests

url = "https://biztoc.p.rapidapi.com/news/source/bbc"

headers = {
	"x-rapidapi-key": "98d34b126dmshd9e0026c2537006p10c39ejsn1cad76109fbc",
	"x-rapidapi-host": "biztoc.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    data = response.json()
    for item in data:
        print(f"Title: {item['title']}")
        print(f"Body: {item['body']}")
        print(f"Published: {item['published']}")
        print(f"Image: {item['img']['s']}")
        print(f"URL: {item['url']}")
else:
    print("Failed to fetch data:", response.status_code)

Title: Farage and NatWest settle dispute over bank account closure
Body: Farage and NatWest settle dispute over bank account closure
NatWest and Nigel Farage have settled the dispute over the closure of one of his bank accounts.
The agreed settlement comes almost two years after the Reform UK leader had his account with Coutts, the prestigious private bank for the…
Published: Wed, 26 Mar 2025 19:19:52 GMT
Image: https://cdn.biztoc.com/058954c045492a73_s.webp
URL: https://www.bbc.com/news/articles/czx79161e2wo?ref=biztoc.com
Title: Faisal Islam: Reeves is in danger of being boxed in by her own rules
Body: The UK's economic prospects are better than expected, but the forecasts are precarious and could easily be derailed.
Published: Wed, 26 Mar 2025 19:07:06 GMT
Image: https://cdn.biztoc.com/ab948b10b82131bf_s.webp
URL: https://www.bbc.com/news/articles/cp8y0yzmgljo?ref=biztoc.com
Title: Housebuilding plans forecast to boost economy by £6.8bn
Body: Housebuilding plans forecast to boost economy by £6.8bn
Housebuilding is forecast to hit a 40-year high, with reforms to the planning system expected to boost the economy by £6.8bn, according to the independent spending watchdog.
The Office for Budget Responsibility (OBR) said changes including…
Published: Wed, 26 Mar 2025 16:15:45 GMT
Image: https://cdn.biztoc.com/e0e56e6a6c714085_s.webp
URL: https://www.bbc.com/news/articles/cy4vj7yk0nyo?ref=biztoc.com
Title: 23andMe users struggle to delete their highly sensitive data
Body: 23andMe users struggle to delete their highly sensitive data
The computer systems of 23andMe have been struggling to cope with the sheer volume of customers racing to delete their data, after the DNA-testing company announced that it was filing for bankruptcy protection.
The firm says it has now…
Published: Wed, 26 Mar 2025 16:42:57 GMT
Image: https://cdn.biztoc.com/499acb3b38545a44_s.webp
URL: https://www.bbc.com/news/articles/cddy8d63262o?ref=biztoc.com
Title: Three ways the Spring Statement could affect you and your money
Body: While the Spring Statement focusses on the wider UK economy, it could have implications for your money.
Published: Wed, 26 Mar 2025 14:42:13 GMT
Image: https://cdn.biztoc.com/4e8e6b59bd0760f9_s.webp
URL: https://www.bbc.com/news/articles/cvged1en8jro?ref=biztoc.com
Title: UK growth forecast halved for this year
Body: UK growth forecast halved for this year
The UK economy is now predicted to grow at a much slower pace this year than previously expected, according to the government's official forecaster.
Presenting her Spring Statement, Chancellor Rachel Reeves said the Office for Budget Responsibility (OBR)…
Published: Wed, 26 Mar 2025 13:11:05 GMT
Image: https://cdn.biztoc.com/45d65104d0616e5b_s.webp
URL: https://www.bbc.com/news/articles/cqjd5rklyrko?ref=biztoc.com
Title: Maternity discrimination case settled for £215k
Body: Maeve Bradley took action against Citibank after it promoted the person who covered her maternity leave.
Published: Wed, 26 Mar 2025 00:24:14 GMT
Image: https://cdn.biztoc.com/4f1e70199b1315c3_s.webp
URL: https://www.bbc.com/news/articles/cvgp0j3jjnmo?ref=biztoc.com
Title: Inflation falls to 2.8% ahead of Spring Statement
Body: Inflation falls to 2.8% ahead of Spring Statement
UK inflation fell to 2.8% in the year to February, driven by changes to women's clothing prices.
The figures come ahead of Chancellor Rachel Reeves' Spring Statement, where she will set out her economic plans.
Published: Wed, 26 Mar 2025 07:17:32 GMT
Image: https://cdn.biztoc.com/28f5d43595442dd9_s.webp
URL: https://www.bbc.com/news/articles/cx2g3wwk01vo?ref=biztoc.com
Title: Reeves to focus on £2bn defence boost in Spring Statement
Body: Reeves to focus on £2bn defence boost in Spring Statement
Chancellor Rachel Reeves is to confirm a £2.2bn increase in defence spending in her Spring Statement, with details of previously announced welfare cuts also to be revealed.
She will argue the UK has to "move quickly in a changing world"…
Published: Tue, 25 Mar 2025 22:27:54 GMT
Image: https://cdn.biztoc.com/b58a23702216a5f6_s.webp
URL: https://www.bbc.com/news/articles/cn4y9v8xwvmo?ref=biztoc.com
Title: Oasis sale 'may have misled fans' says watchdog
Body: CMA concerned that Ticketmaster may have breached consumer protection law for Oasis reunion tour.
Published: Tue, 25 Mar 2025 13:29:03 GMT
Image: https://cdn.biztoc.com/73e1932181f49674_s.webp
URL: https://www.bbc.com/news/articles/cddy85n57j8o?ref=biztoc.com
Title: Cladding tax on new homes delayed for a year
Body: The delay comes after developers warned the tax could hamper the government's housebuilding plans.
Published: Tue, 25 Mar 2025 12:32:40 GMT
Image: https://cdn.biztoc.com/29067bfa516d85e5_s.webp
URL: https://www.bbc.com/news/articles/c0kg0d46527o?ref=biztoc.com
Title: Lower Thames Crossing approved by government
Body: Lower Thames Crossing approved by government
The largest road tunnel in the UK will be built after an £8.3bn plan was approved by the government.
The Lower Thames Crossing would link Tilbury, Essex, and Gravesend in Kent by two tunnels running underneath the River Thames.
National Highways hoped…
Published: Tue, 25 Mar 2025 10:41:08 GMT
Image: https://cdn.biztoc.com/64952168afdc8443_s.webp
URL: https://www.bbc.com/news/articles/crewy5472gxo?ref=biztoc.com
Title: AI job application rise 'risks hiring incapable staff'
Body: AI job application rise 'risks hiring incapable staff'
A growing use of artificial intelligence (AI) in job applications risks employers hiring candidates who cannot do the work, a business owner has said.
Advertising boss James Robinson said he and other business leaders were seeing a "real…
Published: Tue, 25 Mar 2025 06:03:21 GMT
Image: https://cdn.biztoc.com/1485b5225ad9b611_s.webp
URL: https://www.bbc.com/news/articles/cx29z8lyx71o?ref=biztoc.com
Title: 'I could lose £100K despite Woodford redress scheme'
Body: 'I could lose £100K despite Woodford redress scheme'
People who lost tens of thousands of pounds when a star stockpicker's investment fund collapsed say they have been let down by the UK's financial regulator and are calling on MPs to investigate.
Around 300,000 people lost money when Woodford…
Published: Tue, 25 Mar 2025 00:49:47 GMT
Image: https://cdn.biztoc.com/29997895f5f9c92c_s.webp
URL: https://www.bbc.com/news/articles/cx2gw5y8er7o?ref=biztoc.com
Title: Bitcoin in the bush - the crypto mine in remote Zambia
Body: Bitcoin in the bush - the crypto mine in remote Zambia
The roar of the Zambezi is deafening as millions of gallons of water crash over rocks and tumble down rapids.
But there's another sound cutting through the trees of the Zambian bush - the unmistakable high-pitched whine of a bitcoin…
Published: Tue, 25 Mar 2025 05:53:55 GMT
Image: https://cdn.biztoc.com/ec6d9b98fc373087_s.webp
URL: https://www.bbc.com/news/articles/cly4xe373p4o?ref=biztoc.com
Title: Hyundai unveils $21bn US expansion as Trump tariffs loom
Body: Hyundai unveils $21bn US expansion as Trump tariffs loom
South Korean carmaking giant Hyundai has unveiled $21bn (£16.3bn) of investment in the US.
The plan includes a new $5.8bn steel plant in the southern state of Louisiana.
Hyundai also said it will expand its American vehicle production and…
Published: Tue, 25 Mar 2025 04:52:13 GMT
Image: https://cdn.biztoc.com/483f0f0f4595aaef_s.webp
URL: https://www.bbc.com/news/articles/cgkmvdz144vo?ref=biztoc.com
Title: Chinese electric carmaker BYD sales beat Tesla
Body: Chinese electric carmaker BYD sales beat Tesla
Chinese electric vehicle maker BYD has reported annual revenue for 2024 that has leapfrogged rival Tesla.
The Shenzhen-based firm says revenue rose by 29% to come in at 777 billion yuan ($107bn; £83bn), boosted by sales of its hybrid vehicles. This…
Published: Tue, 25 Mar 2025 03:24:09 GMT
Image: https://cdn.biztoc.com/c5bcccf298f20868_s.webp
URL: https://www.bbc.com/news/articles/cd65d583qvzo?ref=biztoc.com
Title: Bitcoin in the bush - the crypto mine in remote Zambia
Body: You've requested a page on a website (www.bbc.co.ukundefined) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (www.bbc.co.ukundefined).
If you are a visitor of this website:
Please try again in a few minutes.
If you are the owner of this…
Published: Tue, 25 Mar 2025 00:06:48 GMT
Image: https://cdn.biztoc.com/43187929f577ea4f_s.webp
URL: https://www.bbc.co.ukundefined/?ref=biztoc.com
Title: Pizza Hut workers accuse franchisee of docking wages
Body: Pizza Hut workers accuse franchisee of docking wages
Pizza Hut workers are accusing a franchise of ''blatantly unlawful'' behaviour alleging it has altered timesheets, docked wages and stopped payments per delivery.
Glenshire Group which runs all 22 Pizza Hut delivery outlets in Scotland has been…
Published: Tue, 25 Mar 2025 00:02:01 GMT
Image: https://cdn.biztoc.com/1ca0528ce353f00d_s.webp
URL: https://www.bbc.com/news/articles/c3w10qnnjvyo?ref=biztoc.com
Title: 'I'll make £12.24 an hour - I live payday to payday'
Body: As the chancellor prepares to update her plans for the economy we hear how ordinary people are tackling their own financial challenges.
Published: Tue, 25 Mar 2025 00:03:36 GMT
Image: https://cdn.biztoc.com/5cfdb1e49606e29a_s.webp
URL: https://www.bbc.com/news/articles/cq6ydljn6nno?ref=biztoc.com
Title: Trump threatens tariffs on buyers of Venezuelan oil
Body: Trump threatens tariffs on buyers of Venezuelan oil
President Donald Trump has threatened to impose tariffs of 25% on US imports from countries that purchase oil from Venezuela.
Trump described the move as a "secondary tariff" aimed at punishing the Latin American country "for numerous reasons",…
Published: Mon, 24 Mar 2025 21:58:37 GMT
Image: https://cdn.biztoc.com/207c5d3516491bb3_s.webp
URL: https://www.bbc.com/news/articles/cvgwjxz1e92o?ref=biztoc.com
Title: Faisal Islam: No tax rises and no return to austerity but will it last?
Body: Faisal Islam: No tax rises and no return to austerity but will it last?
"Definitely not a Budget" is the basic message emerging from the Treasury about Wednesday's economic statement.
There will not just be no red box outside Number 11, there will only be a "thin book" of new policies with a…
Published: Mon, 24 Mar 2025 16:19:53 GMT
Image: https://cdn.biztoc.com/57ebb7f3a292730c_s.webp
URL: https://www.bbc.com/news/articles/c1kjxkkn3mzo?ref=biztoc.com
Title: Heathrow closure deeply concerning, says PM
Body: Sir Keir Starmer says he is 'deeply concerned' about the closure of Heathrow Airport as a result of a power cut caused by a fire on Friday.
Published: Mon, 24 Mar 2025 15:19:41 GMT
Image: https://cdn.biztoc.com/d0824f10926cdaee_s.webp
URL: https://www.bbc.com/news/articles/c1w0xv8q925o?ref=biztoc.com
Title: Morrisons to shut 52 cafes and 17 stores
Body: Morrisons to shut 52 cafes and 17 stores
Supermarket chain Morrisons is to shut 52 cafes and 17 stores putting hundreds of jobs at risk.
The retailer will also close a number of in-store services, like the meat and fish counters, pharmacies and its market kitchens at certain sites in an attempt to…
Published: Mon, 24 Mar 2025 12:54:48 GMT
Image: https://cdn.biztoc.com/3bfff465ea9f7e4f_s.webp
URL: https://www.bbc.com/news/articles/cqx0v5xprz4o?ref=biztoc.com
Title: Reeves confirms 15% cut to Civil Service running costs
Body: Reeves confirms 15% cut to Civil Service running costs
Government running costs will be cut by 15% by the end of the decade, the chancellor has promised.
Rachel Reeves told the BBC savings would be made from back office and administrative roles rather than front-line services.
But unions warned…
Published: Sun, 23 Mar 2025 11:33:31 GMT
Image: https://cdn.biztoc.com/89f422fe424dc374_s.webp
URL: https://www.bbc.com/news/articles/cy5nzy403l0o?ref=biztoc.com
Title: DNA testing site 23andMe files for bankruptcy protection
Body: DNA testing site 23andMe files for bankruptcy protection
Popular DNA testing firm 23andMe has filed for bankruptcy protection, and announced that its co-founder and CEO, Anne Wojcicki, has resigned with immediate effect.
The company will now attempt to sell itself under the supervision of a…
Published: Mon, 24 Mar 2025 06:51:18 GMT
Image: https://cdn.biztoc.com/33542b4096b54007_s.webp
URL: https://www.bbc.com/news/articles/c9q4r9xy9wro?ref=biztoc.com
Title: National Grid confirms Heathrow never lost access to power
Body: National Grid confirms Heathrow never lost access to power
The chief executive of the National Grid has confirmed power was available to keep Heathrow open throughout Friday's shutdown.
In an interview with the Financial Times, John Pettigrew said the fire that knocked out a substation was a…
Published: Mon, 24 Mar 2025 03:51:35 GMT
Image: https://cdn.biztoc.com/915211d68dce4029_s.webp
URL: https://www.bbc.com/news/articles/cdjy4m0n1exo?ref=biztoc.com
Title: Disney's Snow White film tops box office despite bad reviews
Body: Disney's Snow White film tops box office despite bad reviews
Disney's live-action version of the classic fairy-tale Snow White has topped the North American box office chart despite a slew of underwhelming reviews.
The movie has taken an estimated $87.3m (£67.5m) globally during its opening…
Published: Mon, 24 Mar 2025 02:58:23 GMT
Image: https://cdn.biztoc.com/1feeec981f1229c1_s.webp
URL: https://www.bbc.com/news/articles/c74ke77v7rvo?ref=biztoc.com
Title: What makes a rum Jamaican? Question at heart of Caribbean legal dispute
Body: What makes a rum Jamaican? Question at heart of Caribbean legal dispute
Rum is a key part of Jamaica's cultural identity, but what exactly makes a rum Jamaican?
That question is at the centre of a dispute that is continuing to rumble on the Caribbean island, as some producers wish to strengthen…
Published: Mon, 24 Mar 2025 00:05:50 GMT
Image: https://cdn.biztoc.com/8487cbdf4b9970b0_s.webp
URL: https://www.bbc.com/news/articles/cvg1ez63ndvo?ref=biztoc.com
Title: Sort 'pothole plague' or lose cash, councils warned
Body: Councils in England will be asked to publish reports on their repairs or miss out on funding, but critics say long-term thinking is needed.
Published: Mon, 24 Mar 2025 00:02:22 GMT
Image: https://cdn.biztoc.com/9c4c95e78afc3f5d_s.webp
URL: https://www.bbc.com/news/articles/c0eg39e01w8o?ref=biztoc.com
Title: UK mulls big tech tax changes to avoid US tariffs
Body: UK mulls big tech tax changes to avoid US tariffs
UK taxes on big tech firms may be changed as part of a deal to avoid US President Donald Trump's next raft of tariffs, Chancellor Rachel Reeves has suggested.
She said talks are "ongoing" about tweaks to the Digital Services Tax (DST), which…
Published: Sun, 23 Mar 2025 12:02:08 GMT
Image: https://cdn.biztoc.com/b42d2cb30b8a8d56_s.webp
URL: https://www.bbc.com/news/articles/c8j0dgym8w1o?ref=biztoc.com
Title: Investigation ordered into power outage that closed Heathrow
Body: Ed Miliband says there are lessons to be learned after outage led to major flight disruption on Friday.
Published: Sat, 22 Mar 2025 16:44:11 GMT
Image: https://cdn.biztoc.com/c04f7fa9ebbc1e15_s.webp
URL: https://www.bbc.com/news/articles/cgm1krkxrxgo?ref=biztoc.com
Title: Rachel Reeves: I will not 'tax and spend'
Body: In an interview with the BBC's Laura Kuenssberg, the chancellor opened up on the public finances and how she's finding the job.
Published: Sat, 22 Mar 2025 05:46:59 GMT
Image: https://cdn.biztoc.com/54ca418fc26c24c2_s.webp
URL: https://www.bbc.com/news/articles/c78eg7dp9ypo?ref=biztoc.com
Title: Uber offers 20 hours of free childcare in bid to lure female drivers
Body: A union says it should instead pay drivers more so they can take time off with their families.
Published: Fri, 21 Mar 2025 16:11:10 GMT
Image: https://cdn.biztoc.com/b3e9b93393f1ada3_s.webp
URL: https://www.bbc.com/news/articles/cgm1pmdlvx8o?ref=biztoc.com
Title: Heathrow substation fire: What went wrong?
Body: Heathrow substation fire: What went wrong?
Heathrow Airport was shut down and thousands of homes were left without power on Friday after a fire at a nearby electric supply substation.
More than 1,300 flights have been cancelled, passengers are being told not to travel to the airport, and more than…
Published: Fri, 21 Mar 2025 13:36:26 GMT
Image: https://cdn.biztoc.com/7db2e66c6a990008_s.webp
URL: https://www.bbc.com/news/articles/cdjy0g01z1po?ref=biztoc.com
Title: Heathrow closure: What are my rights?
Body: Heathrow closure: What are my rights?
Heathrow Airport is closed all day Friday due to a fire at a nearby electrical substation that supplies it with power.
The UK's busiest airport has warned of significant disruption over the coming days, with at least 1,300 flights in and out cancelled.
What…
Published: Fri, 21 Mar 2025 11:12:49 GMT
Image: https://cdn.biztoc.com/90a5082a1e7791f6_s.webp
URL: https://www.bbc.com/news/articles/cwyde870y89o?ref=biztoc.com
Title: Broadcasters fined £4m for freelance pay collusion
Body: Broadcasters fined £4m for freelance pay collusion
Four of the UK's biggest sports broadcast and production companies have been fined more than £4m for illegally colluding on freelance pay rates.
The UK's competition regulator said the BBC, BT, IMG and ITV must pay a combined £4.24m after being…
Published: Fri, 21 Mar 2025 10:45:58 GMT
Image: https://cdn.biztoc.com/ce6905775d598374_s.webp
URL: https://www.bbc.com/news/articles/ce34q1792d0o?ref=biztoc.com
Title: Government borrowing higher than expected as pressure builds on Reeves
Body: Government borrowing higher than expected in February
UK government borrowing was higher than expected in February, adding pressure to Chancellor Rachel Reeves ahead of her Spring Statement next week.
Borrowing - the difference between spending and income from taxes - was £10.7bn last month,…
Published: Fri, 21 Mar 2025 07:27:22 GMT
Image: https://cdn.biztoc.com/23a4cfc4f6b226bc_s.webp
URL: https://www.bbc.com/news/articles/c0jglw54yvyo?ref=biztoc.com
Title: What are my rights if my flight is cancelled or delayed?
Body: Heathrow Airport will be closed all day Friday due to a fire at a nearby electrical substation that supplies it with power.
The UK's busiest airport has warned of significant disruption over the coming days, with at least 1,300 flights in and out cancelled.
What are your rights if your journey has…
Published: Fri, 21 Mar 2025 06:59:16 GMT
Image: https://cdn.biztoc.com/82ff2f0d80089de5_s.webp
URL: https://www.bbc.co.uk/news/business-61646214?ref=biztoc.com
Title: Heathrow Airport closes all day over power outage
Body: Heathrow Airport closes all day over power outage
Heathrow Airport is closing all day Friday because of a large fire at a nearby electrical substation that supplies it.
The airport is experiencing a "significant power outage" because of the fire, a statement from Heathrow said.
"To maintain the…
Published: Fri, 21 Mar 2025 03:32:18 GMT
Image: https://cdn.biztoc.com/391b66f483d1b895_s.webp
URL: https://www.bbc.com/news/articles/cvg5dg4p2l0o?ref=biztoc.com
Title: Trump uses emergency powers to boost mineral production
Body: Trump uses emergency powers to boost mineral production
US President Donald Trump has invoked emergency powers to expand domestic production of critical minerals as he tries to reduce US reliance on imports from countries like China.
The executive order, which uses cold war era legislation,…
Published: Fri, 21 Mar 2025 03:29:37 GMT
Image: https://cdn.biztoc.com/6c8f847943ea1938_s.webp
URL: https://www.bbc.com/news/articles/cwye089j1zdo?ref=biztoc.com
Title: Tesla vandals face up to 20 years in prison, says attorney general
Body: Tesla vandals face up to 20 years in prison, says attorney general
US Attorney General Pam Bondi said Thursday that three defendants accused of vandalism targeting Elon Musk's Tesla electric vehicle company could face up to 20 years in prison.
Bondi said the damage to Tesla cars, dealerships and…
Published: Fri, 21 Mar 2025 01:20:20 GMT
Image: https://cdn.biztoc.com/5b175fce2a7bd36e_s.webp

## **Gathering Information and Extracting Information**

In [88]:
import pandas as pd

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(response.json())

df

,body,img,published,title,url
0,Farage and NatWest settle dispute over bank ac...,{'s': 'https://cdn.biztoc.com/058954c045492a73...,"Wed, 26 Mar 2025 19:19:52 GMT",Farage and NatWest settle dispute over bank ac...,https://www.bbc.com/news/articles/czx79161e2wo...
1,The UK's economic prospects are better than ex...,{'s': 'https://cdn.biztoc.com/ab948b10b82131bf...,"Wed, 26 Mar 2025 19:07:06 GMT",Faisal Islam: Reeves is in danger of being box...,https://www.bbc.com/news/articles/cp8y0yzmgljo...
2,Housebuilding plans forecast to boost economy ...,{'s': 'https://cdn.biztoc.com/e0e56e6a6c714085...,"Wed, 26 Mar 2025 16:15:45 GMT",Housebuilding plans forecast to boost economy ...,https://www.bbc.com/news/articles/cy4vj7yk0nyo...
3,23andMe users struggle to delete their highly ...,{'s': 'https://cdn.biztoc.com/499acb3b38545a44...,"Wed, 26 Mar 2025 16:42:57 GMT",23andMe users struggle to delete their highly ...,https://www.bbc.com/news/articles/cddy8d63262o...
4,While the Spring Statement focusses on the wid...,{'s': 'https://cdn.biztoc.com/4e8e6b59bd0760f9...,"Wed, 26 Mar 2025 14:42:13 GMT",Three ways the Spring Statement could affect y...,https://www.bbc.com/news/articles/cvged1en8jro...
5,UK growth forecast halved for this year\nThe U...,{'s': 'https://cdn.biztoc.com/45d65104d0616e5b...,"Wed, 26 Mar 2025 13:11:05 GMT",UK growth forecast halved for this year,https://www.bbc.com/news/articles/cqjd5rklyrko...
6,Maeve Bradley took action against Citibank aft...,{'s': 'https://cdn.biztoc.com/4f1e70199b1315c3...,"Wed, 26 Mar 2025 00:24:14 GMT",Maternity discrimination case settled for £215k,https://www.bbc.com/news/articles/cvgp0j3jjnmo...
7,Inflation falls to 2.8% ahead of Spring Statem...,{'s': 'https://cdn.biztoc.com/28f5d43595442dd9...,"Wed, 26 Mar 2025 07:17:32 GMT",Inflation falls to 2.8% ahead of Spring Statement,https://www.bbc.com/news/articles/cx2g3wwk01vo...
8,Reeves to focus on £2bn defence boost in Sprin...,{'s': 'https://cdn.biztoc.com/b58a23702216a5f6...,"Tue, 25 Mar 2025 22:27:54 GMT",Reeves to focus on £2bn defence boost in Sprin...,https://www.bbc.com/news/articles/cn4y9v8xwvmo...
9,CMA concerned that Ticketmaster may have breac...,{'s': 'https://cdn.biztoc.com/73e1932181f49674...,"Tue, 25 Mar 2025 13:29:03 GMT",Oasis sale 'may have misled fans' says watchdog,https://www.bbc.com/news/articles/cddy85n57j8o...
10,The delay comes after developers warned the ta...,{'s': 'https://cdn.biztoc.com/29067bfa516d85e5...,"Tue, 25 Mar 2025 12:32:40 GMT",Cladding tax on new homes delayed for a year,https://www.bbc.com/news/articles/c0kg0d46527o...
11,Lower Thames Crossing approved by government\n...,{'s': 'https://cdn.biztoc.com/64952168afdc8443...,"Tue, 25 Mar 2025 10:41:08 GMT",Lower Thames Crossing approved by government,https://www.bbc.com/news/articles/crewy5472gxo...
12,AI job application rise 'risks hiring incapabl...,{'s': 'https://cdn.biztoc.com/1485b5225ad9b611...,"Tue, 25 Mar 2025 06:03:21 GMT",AI job application rise 'risks hiring incapabl...,https://www.bbc.com/news/articles/cx29z8lyx71o...
13,'I could lose £100K despite Woodford redress s...,{'s': 'https://cdn.biztoc.com/29997895f5f9c92c...,"Tue, 25 Mar 2025 00:49:47 GMT",'I could lose £100K despite Woodford redress s...,https://www.bbc.com/news/articles/cx2gw5y8er7o...
14,Bitcoin in the bush - the crypto mine in remot...,{'s': 'https://cdn.biztoc.com/ec6d9b98fc373087...,"Tue, 25 Mar 2025 05:53:55 GMT",Bitcoin in the bush - the crypto mine in remot...,https://www.bbc.com/news/articles/cly4xe373p4o...
15,Hyundai unveils $21bn US expansion as Trump ta...,{'s': 'https://cdn.biztoc.com/483f0f0f4595aaef...,"Tue, 25 Mar 2025 04:52:13 GMT",Hyundai unveils $21bn US expansion as Trump ta...,https://www.bbc.com/news/articles/cgkmvdz144vo...
16,Chinese electric carmaker BYD sales beat Tesla...,{'s': 'https://cdn.biztoc.com/c5bcccf298f20868...,"Tue, 25 Mar 2025 03:24:09 GMT",Chinese electric carmaker BYD sales beat Tesla,https://www.bbc.com/news/articles/cd65d583qvzo...
17,You've requested a page on a website (www.bbc....,{'s': 'https://cdn.biztoc.com/43187929f577ea4f...,"Tue, 25 Mar 2025 00:06:48 GMT",Bitcoin in the bush - the crypto mine in remot...,https://www.bbc.co.ukundefined/?ref=biztoc.com
18,Pizza Hut workers accuse franchisee of docking...,{'s': 'https://cdn.biztoc.com/1ca0528ce353f00d...,"Tue, 25 Mar 2025 00:02:01 GMT",Pizza Hut workers accuse franchisee of docking...,https://www.bbc.com/news/articles/c3w10qnnjvyo...
19,As the chancellor prepares to update her plans...,{'s': 'https://cdn.biztoc.com/5cfdb1e49606e29a...,"Tue, 25 Mar 2025 00:03:36 GMT",'I'll make £12.24 an hour - I live payday to p...,https://www.bbc.com/news/articles/cq6ydljn6nno...
20,Trump threatens tariffs on buyers of Venezuela...,{'s': 'https://cdn.biztoc.com/207c5d3516491bb3...,"Mon, 24 Mar 2025 21:58:37 GMT",Trump threatens tariffs on buyers of Venezuela...,https://www.bbc.com/news/articles/cvgwjxz1e92o...
21,Faisal Islam: No tax rises and no return to au...,{'s': 'https://cdn.biztoc.com/57ebb7f3a292730c...,"Mon, 24 Mar 2025 16:19:53 GMT",Faisal Islam: No tax rises and no return to au...,https://www.bbc.com/news/articles/c1kjxkkn3mzo...
22,Sir Keir Starmer says he is 'deeply concerned'...,{'s': 'https://cdn.biztoc.com/d0824f10926cdaee...,"Mon, 24 Mar 2025 15:19:41 GMT","Heathrow closure deeply concerning, says PM",https://www.bbc.com/news/articles/c1w0xv8q925o...
23,Morrisons to shut 52 cafes and 17 stores\nSupe...,{'s': 'https://cdn.biztoc.com/3bfff465ea9f7e4f...,"Mon, 24 Mar 2025 12:54:48 GMT",Morrisons to shut 52 cafes and 17 stores,https://www.bbc.com/news/articles/cqx0v5xprz4o...
24,Reeves confirms 15% cut to Civil Service runni...,{'s': 'https://cdn.biztoc.com/89f422fe424dc374...,"Sun, 23 Mar 2025 11:33:31 GMT",Reeves confirms 15% cut to Civil Service runni...,https://www.bbc.com/news/articles/cy5nzy403l0o...
25,DNA testing site 23andMe files for bankruptcy ...,{'s': 'https://cdn.biztoc.com/33542b4096b54007...,"Mon, 24 Mar 2025 06:51:18 GMT",DNA testing site 23andMe files for bankruptcy ...,https://www.bbc.com/news/articles/c9q4r9xy9wro...
26,National Grid confirms Heathrow never lost acc...,{'s': 'https://cdn.biztoc.com/915211d68dce4029...,"Mon, 24 Mar 2025 03:51:35 GMT",National Grid confirms Heathrow never lost acc...,https://www.bbc.com/news/articles/cdjy4m0n1exo...
27,Disney's Snow White film tops box office despi...,{'s': 'https://cdn.biztoc.com/1feeec981f1229c1...,"Mon, 24 Mar 2025 02:58:23 GMT",Disney's Snow White film tops box office despi...,https://www.bbc.com/news/articles/c74ke77v7rvo...
28,What makes a rum Jamaican? Question at heart o...,{'s': 'https://cdn.biztoc.com/8487cbdf4b9970b0...,"Mon, 24 Mar 2025 00:05:50 GMT",What makes a rum Jamaican? Question at heart o...,https://www.bbc.com/news/articles/cvg1ez63ndvo...
29,Councils in England will be asked to publish r...,{'s': 'https://cdn.biztoc.com/9c4c95e78afc3f5d...,"Mon, 24 Mar 2025 00:02:22 GMT","Sort 'pothole plague' or lose cash, councils w...",https://www.bbc.com/news/articles/c0eg39e01w8o...
30,UK mulls big tech tax changes to avoid US tari...,{'s': 'https://cdn.biztoc.com/b42d2cb30b8a8d56...,"Sun, 23 Mar 2025 12:02:08 GMT",UK mulls big tech tax changes to avoid US tariffs,https://www.bbc.com/news/articles/c8j0dgym8w1o...
31,Ed Miliband says there are lessons to be learn...,{'s': 'https://cdn.biztoc.com/c04f7fa9ebbc1e15...,"Sat, 22 Mar 2025 16:44:11 GMT",Investigation ordered into power outage that c...,https://www.bbc.com/news/articles/cgm1krkxrxgo...
32,In an interview with the BBC's Laura Kuenssber...,{'s': 'https://cdn.biztoc.com/54ca418fc26c24c2...,"Sat, 22 Mar 2025 05:46:59 GMT",Rachel Reeves: I will not 'tax and spend',https://www.bbc.com/news/articles/c78eg7dp9ypo...
33,A union says it should instead pay drivers mor...,{'s': 'https://cdn.biztoc.com/b3e9b93393f1ada3...,"Fri, 21 Mar 2025 16:11:10 GMT",Uber offers 20 hours of free childcare in bid ...,https://www.bbc.com/news/articles/cgm1pmdlvx8o...
34,Heathrow substation fire: What went wrong?\nHe...,{'s': 'https://cdn.biztoc.com/7db2e66c6a990008...,"Fri, 21 Mar 2025 13:36:26 GMT",Heathrow substation fire: What went wrong?,https://www.bbc.com/news/articles/cdjy0g01z1po...
35,Heathrow closure: What are my rights?\nHeathro...,{'s': 'https://cdn.biztoc.com/90a5082a1e7791f6...,"Fri, 21 Mar 2025 11:12:49 GMT",Heathrow closure: What are my rights?,https://www.bbc.com/news/articles/cwyde870y89o...
36,Broadcasters fined £4m for freelance pay collu...,{'s': 'https://cdn.biztoc.com/ce6905775d598374...,"Fri, 21 Mar 2025 10:45:58 GMT",Broadcasters fined £4m for freelance pay collu...,https://www.bbc.com/news/articles/ce34q1792d0o...
37,Government borrowing higher than expected in F...,{'s': 'https://cdn.biztoc.com/23a4cfc4f6b226bc...,"Fri, 21 Mar 2025 07:27:22 GMT",Government borrowing higher than expected as p...,https://www.bbc.com/news/articles/c0jglw54yvyo...
38,Heathrow Airport will be closed all day Friday...,{'s': 'https://cdn.biztoc.com/82ff2f0d80089de5...,"Fri, 21 Mar 2025 06:59:16 GMT",What are my rights if my flight is cancelled o...,https://www.bbc.co.uk/news/business-61646214?r...
39,Heathrow Airport closes all day over power out...,{'s': 'https://cdn.biztoc.com/391b66f483d1b895...,"Fri, 21 Mar 2025 03:32:18 GMT",Heathrow Airport closes all day over power outage,https://www.bbc.com/news/articles/cvg5dg4p2l0o...
40,Trump uses emergency powers to boost mineral p...,{'s': 'https://cdn.biztoc.com/6c8f847943ea1938...,"Fri, 21 Mar 2025 03:29:37 GMT",Trump uses emergency powers to boost mineral p...,https://www.bbc.com/news/articles/cwye089j1zdo...
41,"Tesla vandals face up to 20 years in prison, s...",{'s': 'https://cdn.biztoc.com/5b175fce2a7bd36e...,"Fri, 21 Mar 2025 01:20:20 GMT","Tesla vandals face up to 20 years in prison, s...",https://www.bbc.com/news/articles/c204yvv1eexo...
42,"The chatbot has become an ""unfiltered and unhi...",{'s': 'https://cdn.biztoc.com/e33db2ccdeffe1a6...,"Thu, 20 Mar 2025 22:51:08 GMT",Why Elon Musk's Grok is kicking up a storm in ...,https://www.bbc.com/news/articles/cd65p1pv8pdo...
43,TikTokers call for 'chubby filter' to be banne...,{'s': 'https://cdn.biztoc.com/bfbf4692cfa0b907...,"Fri, 21 Mar 2025 00:02:37 GMT",TikTokers call for 'chubby filter' to be banned,https://www.bbc.com/news/articles/c4gmvjvv6vjo...
44,The slow but steady advance of driverless vehi...,{'s': 'https://cdn.biztoc.com/adda905c09887d9d...,"Fri, 21 Mar 2025 00:02:48 GMT",The slow but steady advance of driverless vehi...,https://www.bbc.com/news/articles/cly41yx9w88o...
45,Engineers are building a helicopter that is se...,{'s': 'https://cdn.biztoc.com/396bb702609c630f...,"Thu, 20 Mar 2025 17:51:24 GMT",Engineers building 'helicopter that flies itself',https://www.bbc.com/news/articles/c7vzy9zndyqo...
46,Tesla makes largest ever Cybertruck recall\nTh...,{'s': 'https://cdn.biztoc.com/58460be1ca706ec3...,"Thu, 20 Mar 2025 18:47:55 GMT",Tesla makes largest ever Cybertruck recall,https://www.bbc.com/news/articles/c0kgy20x0x4o...
47,Family sues Boeing over whistleblower death\nT...,{'s': 'https://cdn.biztoc.com/cbab1c886f7607f0...,"Thu, 20 Mar 2025 16:24:49 GMT",Family sues Boeing over whistleblower death,https://www.bbc.com/news/articles/cwyje8e8rdlo...
48,EU delays plans to retaliate against Trump tar...,{'s': 'https://cdn.biztoc.com/1ef719daee2a2290...,"Thu, 20 Mar 2025 16:10:19 GMT",EU delays plans to retaliate against Trump tar...,https://www.bbc.com/news/articles/c62z157jvd8o...
49,More than a fifth of UK adults still not looki...,{'s': 'https://cdn.biztoc.com/c1e53579bb857c20...,"Thu, 20 Mar 2025 07:36:33 GMT",More than a fifth of UK adults still not looki...,https://www.bbc.com/news/articles/cdrx4d37dnjo...
50,You're hired: Lord Sugar signs up to stay on T...,{'s': 'https://cdn.biztoc.com/607b8be6e9bbb280...,"Thu, 20 Mar 2025 01:45:51 GMT",You're hired: Lord Sugar signs up to stay on T...,https://www.bbc.com/news/articles/c20d8jlnkk8o...
51,The company is still valued at more than 100 t...,{'s': 'https://cdn.biztoc.com/7c9fe0a9425bcf84...,"Thu, 20 Mar 2025 00:05:40 GMT",Tesla's challenges run deeper than 'toxic' con...,https://www.bbc.com/news/articles/cz61vwjel2zo...
52,Bank of England expected to hold interest rate...,{'s': 'https://cdn.biztoc.com/44d44f3973cf5206...,"Thu, 20 Mar 2025 00:06:51 GMT",Bank of England expected to hold interest rate...,https://www.bbc.com/news/articles/ckgz82838l8o...
53,A report by parliament's cross-party-transport...,{'s': 'https://cdn.biztoc.com/2877045a841f2d25...,"Thu, 20 Mar 2025 00:06:55 GMT","Disabled travel access an 'embarrassment', MPs...",https://www.bbc.com/news/articles/cd925n7qxnqo...
54,Will Trump's tariff war spark big-bang reforms...,{'s': 'https://cdn.biztoc.com/0523134df39efc32...,"Wed, 19 Mar 2025 22:27:16 GMT",Will Trump's tariff war spark big-bang reforms...,https://www.bbc.com/news/articles/cd0nr05yxmzo...
55,US holds rates steady despite economy fears\nT...,{'s': 'https://cdn.biztoc.com/363289c0ff0ffe3f...,"Wed, 19 Mar 2025 18:35:30 GMT",US holds rates steady despite economy fears,https://www.bbc.com/news/articles/cvgp574lvdxo...
56,Brewer to increase prices following tax rise\n...,{'s': 'https://cdn.biztoc.com/e9f5f73415ea3452...,"Wed, 19 Mar 2025 12:34:58 GMT",Brewer to increase prices following tax rise,https://www.bbc.com/news/articles/cd925d0k33jo...
57,"Interest rates, set by the Bank of England, af...",{'s': 'https://cdn.biztoc.com/f6c4b4b6a65f0132...,"Wed, 19 Mar 2025 11:46:19 GMT",When will interest rates go down again?,https://www.bbc.co.uk/news/business-57764601?r...
58,Ben & Jerry's says its boss ousted by Unilever...,{'s': 'https://cdn.biztoc.com/d7c4e44caebc9e2a...,"Wed, 19 Mar 2025 08:53:50 GMT",Ben & Jerry's says its boss ousted by Unilever,https://www.bbc.com/news/articles/ckg8pk9rpx4o...
59,Santander to close 95 branches with 750 jobs a...,{'s': 'https://cdn.biztoc.com/193ba7d2436de44a...,"Wed, 19 Mar 2025 08:05:32 GMT",Santander to close 95 branches with 750 jobs a...,https://www.bbc.com/news/articles/ceqjp4lvr4wo...

In [89]:
len(df)

60

In [90]:
print(df.columns.tolist())

['body', 'img', 'published', 'title', 'url']

In [91]:
for (columnName, columnData) in df.items():
    print('Column Name : ', columnName[0])
    print('Column Contents : ', columnData.values)

Column Name :  b
Column Contents :  ['Farage and NatWest settle dispute over bank account closure\nNatWest and Nigel Farage have settled the dispute over the closure of one of his bank accounts.\nThe agreed settlement comes almost two years after the Reform UK leader had his account with Coutts, the prestigious private bank for the…'
 "The UK's economic prospects are better than expected, but the forecasts are precarious and could easily be derailed."
 'Housebuilding plans forecast to boost economy by £6.8bn\nHousebuilding is forecast to hit a 40-year high, with reforms to the planning system expected to boost the economy by £6.8bn, according to the independent spending watchdog.\nThe Office for Budget Responsibility (OBR) said changes including…'
 '23andMe users struggle to delete their highly sensitive data\nThe computer systems of 23andMe have been struggling to cope with the sheer volume of customers racing to delete their data, after the DNA-testing company announced that it was filing for bankruptcy protection.\nThe firm says it has now…'
 'While the Spring Statement focusses on the wider UK economy, it could have implications for your money.'
 "UK growth forecast halved for this year\nThe UK economy is now predicted to grow at a much slower pace this year than previously expected, according to the government's official forecaster.\nPresenting her Spring Statement, Chancellor Rachel Reeves said the Office for Budget Responsibility (OBR)…"
 'Maeve Bradley took action against Citibank after it promoted the person who covered her maternity leave.'
 "Inflation falls to 2.8% ahead of Spring Statement\nUK inflation fell to 2.8% in the year to February, driven by changes to women's clothing prices.\nThe figures come ahead of Chancellor Rachel Reeves' Spring Statement, where she will set out her economic plans."
 'Reeves to focus on £2bn defence boost in Spring Statement\nChancellor Rachel Reeves is to confirm a £2.2bn increase in defence spending in her Spring Statement, with details of previously announced welfare cuts also to be revealed.\nShe will argue the UK has to "move quickly in a changing world"…'
 'CMA concerned that Ticketmaster may have breached consumer protection law for Oasis reunion tour.'
 "The delay comes after developers warned the tax could hamper the government's housebuilding plans."
 'Lower Thames Crossing approved by government\nThe largest road tunnel in the UK will be built after an £8.3bn plan was approved by the government.\nThe Lower Thames Crossing would link Tilbury, Essex, and Gravesend in Kent by two tunnels running underneath the River Thames.\nNational Highways hoped…'
 'AI job application rise \'risks hiring incapable staff\'\nA growing use of artificial intelligence (AI) in job applications risks employers hiring candidates who cannot do the work, a business owner has said.\nAdvertising boss James Robinson said he and other business leaders were seeing a "real…'
 "'I could lose £100K despite Woodford redress scheme'\nPeople who lost tens of thousands of pounds when a star stockpicker's investment fund collapsed say they have been let down by the UK's financial regulator and are calling on MPs to investigate.\nAround 300,000 people lost money when Woodford…"
 "Bitcoin in the bush - the crypto mine in remote Zambia\nThe roar of the Zambezi is deafening as millions of gallons of water crash over rocks and tumble down rapids.\nBut there's another sound cutting through the trees of the Zambian bush - the unmistakable high-pitched whine of a bitcoin…"
 'Hyundai unveils $21bn US expansion as Trump tariffs loom\nSouth Korean carmaking giant Hyundai has unveiled $21bn (£16.3bn) of investment in the US.\nThe plan includes a new $5.8bn steel plant in the southern state of Louisiana.\nHyundai also said it will expand its American vehicle production and…'
 'Chinese electric carmaker BYD sales beat Tesla\nChinese electric vehicle maker BYD has reported annual revenue for 2024 that has leapfrogged rival Tesla.\nThe Shenzhen-based firm says revenue rose by 29% to come in at 777 billion yuan ($107bn; £83bn), boosted by sales of its hybrid vehicles. This…'
 "You've requested a page on a website (www.bbc.co.ukundefined) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (www.bbc.co.ukundefined).\nIf you are a visitor of this website:\nPlease try again in a few minutes.\nIf you are the owner of this…"
 "Pizza Hut workers accuse franchisee of docking wages\nPizza Hut workers are accusing a franchise of ''blatantly unlawful'' behaviour alleging it has altered timesheets, docked wages and stopped payments per delivery.\nGlenshire Group which runs all 22 Pizza Hut delivery outlets in Scotland has been…"
 'As the chancellor prepares to update her plans for the economy we hear how ordinary people are tackling their own financial challenges.'
 'Trump threatens tariffs on buyers of Venezuelan oil\nPresident Donald Trump has threatened to impose tariffs of 25% on US imports from countries that purchase oil from Venezuela.\nTrump described the move as a "secondary tariff" aimed at punishing the Latin American country "for numerous reasons",…'
 'Faisal Islam: No tax rises and no return to austerity but will it last?\n"Definitely not a Budget" is the basic message emerging from the Treasury about Wednesday\'s economic statement.\nThere will not just be no red box outside Number 11, there will only be a "thin book" of new policies with a…'
 "Sir Keir Starmer says he is 'deeply concerned' about the closure of Heathrow Airport as a result of a power cut caused by a fire on Friday."
 'Morrisons to shut 52 cafes and 17 stores\nSupermarket chain Morrisons is to shut 52 cafes and 17 stores putting hundreds of jobs at risk.\nThe retailer will also close a number of in-store services, like the meat and fish counters, pharmacies and its market kitchens at certain sites in an attempt to…'
 'Reeves confirms 15% cut to Civil Service running costs\nGovernment running costs will be cut by 15% by the end of the decade, the chancellor has promised.\nRachel Reeves told the BBC savings would be made from back office and administrative roles rather than front-line services.\nBut unions warned…'
 'DNA testing site 23andMe files for bankruptcy protection\nPopular DNA testing firm 23andMe has filed for bankruptcy protection, and announced that its co-founder and CEO, Anne Wojcicki, has resigned with immediate effect.\nThe company will now attempt to sell itself under the supervision of a…'
 "National Grid confirms Heathrow never lost access to power\nThe chief executive of the National Grid has confirmed power was available to keep Heathrow open throughout Friday's shutdown.\nIn an interview with the Financial Times, John Pettigrew said the fire that knocked out a substation was a…"
 "Disney's Snow White film tops box office despite bad reviews\nDisney's live-action version of the classic fairy-tale Snow White has topped the North American box office chart despite a slew of underwhelming reviews.\nThe movie has taken an estimated $87.3m (£67.5m) globally during its opening…"
 "What makes a rum Jamaican? Question at heart of Caribbean legal dispute\nRum is a key part of Jamaica's cultural identity, but what exactly makes a rum Jamaican?\nThat question is at the centre of a dispute that is continuing to rumble on the Caribbean island, as some producers wish to strengthen…"
 'Councils in England will be asked to publish reports on their repairs or miss out on funding, but critics say long-term thinking is needed.'
 'UK mulls big tech tax changes to avoid US tariffs\nUK taxes on big tech firms may be changed as part of a deal to avoid US President Donald Trump\'s next raft of tariffs, Chancellor Rachel Reeves has suggested.\nShe said talks are "ongoing" about tweaks to the Digital Services Tax (DST), which…'
 'Ed Miliband says there are lessons to be learned after outage led to major flight disruption on Friday.'
 "In an interview with the BBC's Laura Kuenssberg, the chancellor opened up on the public finances and how she's finding the job."
 'A union says it should instead pay drivers more so they can take time off with their families.'
 'Heathrow substation fire: What went wrong?\nHeathrow Airport was shut down and thousands of homes were left without power on Friday after a fire at a nearby electric supply substation.\nMore than 1,300 flights have been cancelled, passengers are being told not to travel to the airport, and more than…'
 "Heathrow closure: What are my rights?\nHeathrow Airport is closed all day Friday due to a fire at a nearby electrical substation that supplies it with power.\nThe UK's busiest airport has warned of significant disruption over the coming days, with at least 1,300 flights in and out cancelled.\nWhat…"
 "Broadcasters fined £4m for freelance pay collusion\nFour of the UK's biggest sports broadcast and production companies have been fined more than £4m for illegally colluding on freelance pay rates.\nThe UK's competition regulator said the BBC, BT, IMG and ITV must pay a combined £4.24m after being…"
 'Government borrowing higher than expected in February\nUK government borrowing was higher than expected in February, adding pressure to Chancellor Rachel Reeves ahead of her Spring Statement next week.\nBorrowing - the difference between spending and income from taxes - was £10.7bn last month,…'
 "Heathrow Airport will be closed all day Friday due to a fire at a nearby electrical substation that supplies it with power.\nThe UK's busiest airport has warned of significant disruption over the coming days, with at least 1,300 flights in and out cancelled.\nWhat are your rights if your journey has…"
 'Heathrow Airport closes all day over power outage\nHeathrow Airport is closing all day Friday because of a large fire at a nearby electrical substation that supplies it.\nThe airport is experiencing a "significant power outage" because of the fire, a statement from Heathrow said.\n"To maintain the…'
 'Trump uses emergency powers to boost mineral production\nUS President Donald Trump has invoked emergency powers to expand domestic production of critical minerals as he tries to reduce US reliance on imports from countries like China.\nThe executive order, which uses cold war era legislation,…'
 "Tesla vandals face up to 20 years in prison, says attorney general\nUS Attorney General Pam Bondi said Thursday that three defendants accused of vandalism targeting Elon Musk's Tesla electric vehicle company could face up to 20 years in prison.\nBondi said the damage to Tesla cars, dealerships and…"
 'The chatbot has become an "unfiltered and unhinged" digital sensation in India.'
 'TikTokers call for \'chubby filter\' to be banned\nTikTok users have told the BBC they think a viral tool which makes people appear overweight should be banned from the platform.\nKnown as a "chubby filter", the artificial intelligence (AI) tool takes a photo of a person and edits their appearance to…'
 "The slow but steady advance of driverless vehicles\nMike Johns didn't expect his return trip from Los Angeles to Scottsdale, Arizona in December to go viral.\nTo get to the airport he booked a driverless taxi and enjoyed a thrill when he jumped in with curious bystanders looking on.\nBut he got much…"
 'Engineers are building a helicopter that is set to fly itself - without humans operating it remotely.'
 "Tesla makes largest ever Cybertruck recall\nThousands of Tesla Cybertrucks have been recalled in the US due to concerns about part of the electric car's trim falling off in the model's eighth and largest ever recall.\nThe issue affects more than 46,000 trucks made in 2024 and 2025, which analysts…"
 'Family sues Boeing over whistleblower death\nThis story contains details of someone taking their own life, which some readers may find distressing.\nThe family of a Boeing whistleblower who took his own life last year has filed a wrongful death lawsuit against the company.\nThe complaint alleges that…'
 "EU delays plans to retaliate against Trump tariffs\nThe European Union (EU) has delayed plans to hit back at US President Donald Trump's steel and aluminium tariffs until the middle of next month.\nThe trading bloc was set to impose duties on US products, including a 50% levy on whiskey, from 1…"
 'More than a fifth of UK adults still not looking for work\nMore than a fifth of UK working-age adults are still not in work or actively looking for work, official figures suggest.\nThe UK economic inactivity rate was 21.5% in the three months to January, marking a drop from both the previous quarter…'
 "You're hired: Lord Sugar signs up to stay on The Apprentice into his 80s\nLord Sugar has signed a new three-year deal with the BBC to stay on The Apprentice.\nThe billionaire was already contracted to do the 20th series of the show next year, but says he has signed to do three more series, taking…"
 'The company is still valued at more than 100 times its earnings - but it faces problems that experts say go beyond questions around its CEO'
 'Bank of England expected to hold interest rates at 4.5%\nThe Bank of England is expected to keep interest rates on hold when policymakers announce their latest decision on Thursday.\nThe Bank rate heavily influences the cost of borrowing for households, businesses and the government, as well as…'
 'A report by parliament\'s cross-party-transport select committee says accessibility failings are "systematic" across all modes of transport.'
 "Will Trump's tariff war spark big-bang reforms in India?\nIndia has usually turned to economic reforms in times of distress, with the most famous example being 1991, when the country embraced liberalisation in the face of a deep financial crisis.\nNow, with US President Donald Trump's tit-for-tat…"
 "US holds rates steady despite economy fears\nThe US central bank has kept interest rates unchanged for the second time in a row, while warning that economic uncertainty had increased.\nThe decision, which was widely expected, left the Federal Reserve's benchmark interest rate hovering around 4.3%,…"
 "Brewer to increase prices following tax rise\nBritain's oldest brewer has said it will hike its beer prices in response to rising taxes and wage costs taking effect in April.\nShepherd Neame, which is based in Faversham, Kent, and runs 290 pubs primarily in the South East, said the two policies…"
 'Interest rates, set by the Bank of England, affect mortgage, loan and savings rates for millions.'
 "Ben & Jerry's says its boss ousted by Unilever\nBen & Jerry's has said its chief executive, David Stever, was being removed by its parent company, Unilever, in a growing dispute over the ice cream company's political activism.\nThe allegation was part of a legal case filed in a US court by Ben &…"
 'Santander to close 95 branches with 750 jobs at risk\nSantander has announced it is set to close 95 branches across the UK, putting 750 jobs at risk.\nThe High Street bank said its customers were increasingly shifting to banking online and it was aiming to start closing branches from June.\nAs part…']
Column Name :  i
Column Contents :  [{'s': 'https://cdn.biztoc.com/058954c045492a73_s.webp', 'sq': 'https://cdn.biztoc.com/058954c045492a73_sq.webp'}
 {'s': 'https://cdn.biztoc.com/ab948b10b82131bf_s.webp', 'sq': 'https://cdn.biztoc.com/ab948b10b82131bf_sq.webp'}
 {'s': 'https://cdn.biztoc.com/e0e56e6a6c714085_s.webp', 'sq': 'https://cdn.biztoc.com/e0e56e6a6c714085_sq.webp'}
 {'s': 'https://cdn.biztoc.com/499acb3b38545a44_s.webp', 'sq': 'https://cdn.biztoc.com/499acb3b38545a44_sq.webp'}
 {'s': 'https://cdn.biztoc.com/4e8e6b59bd0760f9_s.webp', 'sq': 'https://cdn.biztoc.com/4e8e6b59bd0760f9_sq.webp'}
 {'s': 'https://cdn.biztoc.com/45d65104d0616e5b_s.webp', 'sq': 'https://cdn.biztoc.com/45d65104d0616e5b_sq.webp'}
 {'s': 'https://cdn.biztoc.com/4f1e70199b1315c3_s.webp', 'sq': 'https://cdn.biztoc.com/4f1e70199b1315c3_sq.webp'}
 {'s': 'https://cdn.biztoc.com/28f5d43595442dd9_s.webp', 'sq': 'https://cdn.biztoc.com/28f5d43595442dd9_sq.webp'}
 {'s': 'https://cdn.biztoc.com/b58a23702216a5f6_s.webp', 'sq': 'https://cdn.biztoc.com/b58a23702216a5f6_sq.webp'}
 {'s': 'https://cdn.biztoc.com/73e1932181f49674_s.webp', 'sq': 'https://cdn.biztoc.com/73e1932181f49674_sq.webp'}
 {'s': 'https://cdn.biztoc.com/29067bfa516d85e5_s.webp', 'sq': 'https://cdn.biztoc.com/29067bfa516d85e5_sq.webp'}
 {'s': 'https://cdn.biztoc.com/64952168afdc8443_s.webp', 'sq': 'https://cdn.biztoc.com/64952168afdc8443_sq.webp'}
 {'s': 'https://cdn.biztoc.com/1485b5225ad9b611_s.webp', 'sq': 'https://cdn.biztoc.com/1485b5225ad9b611_sq.webp'}
 {'s': 'https://cdn.biztoc.com/29997895f5f9c92c_s.webp', 'sq': 'https://cdn.biztoc.com/29997895f5f9c92c_sq.webp'}
 {'s': 'https://cdn.biztoc.com/ec6d9b98fc373087_s.webp', 'sq': 'https://cdn.biztoc.com/ec6d9b98fc373087_sq.webp'}
 {'s': 'https://cdn.biztoc.com/483f0f0f4595aaef_s.webp', 'sq': 'https://cdn.biztoc.com/483f0f0f4595aaef_sq.webp'}
 {'s': 'https://cdn.biztoc.com/c5bcccf298f20868_s.webp', 'sq': 'https://cdn.biztoc.com/c5bcccf298f20868_sq.webp'}
 {'s': 'https://cdn.biztoc.com/43187929f577ea4f_s.webp', 'sq': 'https://cdn.biztoc.com/43187929f577ea4f_sq.webp'}
 {'s': 'https://cdn.biztoc.com/1ca0528ce353f00d_s.webp', 'sq': 'https://cdn.biztoc.com/1ca0528ce353f00d_sq.webp'}
 {'s': 'https://cdn.biztoc.com/5cfdb1e49606e29a_s.webp', 'sq': 'https://cdn.biztoc.com/5cfdb1e49606e29a_sq.webp'}
 {'s': 'https://cdn.biztoc.com/207c5d3516491bb3_s.webp', 'sq': 'https://cdn.biztoc.com/207c5d3516491bb3_sq.webp'}
 {'s': 'https://cdn.biztoc.com/57ebb7f3a292730c_s.webp', 'sq': 'https://cdn.biztoc.com/57ebb7f3a292730c_sq.webp'}
 {'s': 'https://cdn.biztoc.com/d0824f10926cdaee_s.webp', 'sq': 'https://cdn.biztoc.com/d0824f10926cdaee_sq.webp'}
 {'s': 'https://cdn.biztoc.com/3bfff465ea9f7e4f_s.webp', 'sq': 'https://cdn.biztoc.com/3bfff465ea9f7e4f_sq.webp'}
 {'s': 'https://cdn.biztoc.com/89f422fe424dc374_s.webp', 'sq': 'https://cdn.biztoc.com/89f422fe424dc374_sq.webp'}
 {'s': 'https://cdn.biztoc.com/33542b4096b54007_s.webp', 'sq': 'https://cdn.biztoc.com/33542b4096b54007_sq.webp'}
 {'s': 'https://cdn.biztoc.com/915211d68dce4029_s.webp', 'sq': 'https://cdn.biztoc.com/915211d68dce4029_sq.webp'}
 {'s': 'https://cdn.biztoc.com/1feeec981f1229c1_s.webp', 'sq': 'https://cdn.biztoc.com/1feeec981f1229c1_sq.webp'}
 {'s': 'https://cdn.biztoc.com/8487cbdf4b9970b0_s.webp', 'sq': 'https://cdn.biztoc.com/8487cbdf4b9970b0_sq.webp'}
 {'s': 'https://cdn.biztoc.com/9c4c95e78afc3f5d_s.webp', 'sq': 'https://cdn.biztoc.com/9c4c95e78afc3f5d_sq.webp'}
 {'s': 'https://cdn.biztoc.com/b42d2cb30b8a8d56_s.webp', 'sq': 'https://cdn.biztoc.com/b42d2cb30b8a8d56_sq.webp'}
 {'s': 'https://cdn.biztoc.com/c04f7fa9ebbc1e15_s.webp', 'sq': 'https://cdn.biztoc.com/c04f7fa9ebbc1e15_sq.webp'}
 {'s': 'https://cdn.biztoc.com/54ca418fc26c24c2_s.webp', 'sq': 'https://cdn.biztoc.com/54ca418fc26c24c2_sq.webp'}
 {'s': 'https://cdn.biztoc.com/b3e9b93393f1ada3_s.webp', 'sq': 'https://cdn.biztoc.com/b3e9b93393f1ada3_sq.webp'}
 {'s': 'https://cdn.biztoc.com/7db2e66c6a990008_s.webp', 'sq': 'https://cdn.biztoc.com/7db2e66c6a990008_sq.webp'}
 {'s': 'https://cdn.biztoc.com/90a5082a1e7791f6_s.webp', 'sq': 'https://cdn.biztoc.com/90a5082a1e7791f6_sq.webp'}
 {'s': 'https://cdn.biztoc.com/ce6905775d598374_s.webp', 'sq': 'https://cdn.biztoc.com/ce6905775d598374_sq.webp'}
 {'s': 'https://cdn.biztoc.com/23a4cfc4f6b226bc_s.webp', 'sq': 'https://cdn.biztoc.com/23a4cfc4f6b226bc_sq.webp'}
 {'s': 'https://cdn.biztoc.com/82ff2f0d80089de5_s.webp', 'sq': 'https://cdn.biztoc.com/82ff2f0d80089de5_sq.webp'}
 {'s': 'https://cdn.biztoc.com/391b66f483d1b895_s.webp', 'sq': 'https://cdn.biztoc.com/391b66f483d1b895_sq.webp'}
 {'s': 'https://cdn.biztoc.com/6c8f847943ea1938_s.webp', 'sq': 'https://cdn.biztoc.com/6c8f847943ea1938_sq.webp'}
 {'s': 'https://cdn.biztoc.com/5b175fce2a7bd36e_s.webp', 'sq': 'https://cdn.biztoc.com/5b175fce2a7bd36e_sq.webp'}

In [92]:
df['body'].values

array(['Farage and NatWest settle dispute over bank account closure\nNatWest and Nigel Farage have settled the dispute over the closure of one of his bank accounts.\nThe agreed settlement comes almost two years after the Reform UK leader had his account with Coutts, the prestigious private bank for the…',
       "The UK's economic prospects are better than expected, but the forecasts are precarious and could easily be derailed.",
       'Housebuilding plans forecast to boost economy by £6.8bn\nHousebuilding is forecast to hit a 40-year high, with reforms to the planning system expected to boost the economy by £6.8bn, according to the independent spending watchdog.\nThe Office for Budget Responsibility (OBR) said changes including…',
       '23andMe users struggle to delete their highly sensitive data\nThe computer systems of 23andMe have been struggling to cope with the sheer volume of customers racing to delete their data, after the DNA-testing company announced that it was filing for bankruptcy protection.\nThe firm says it has now…',
       'While the Spring Statement focusses on the wider UK economy, it could have implications for your money.',
       "UK growth forecast halved for this year\nThe UK economy is now predicted to grow at a much slower pace this year than previously expected, according to the government's official forecaster.\nPresenting her Spring Statement, Chancellor Rachel Reeves said the Office for Budget Responsibility (OBR)…",
       'Maeve Bradley took action against Citibank after it promoted the person who covered her maternity leave.',
       "Inflation falls to 2.8% ahead of Spring Statement\nUK inflation fell to 2.8% in the year to February, driven by changes to women's clothing prices.\nThe figures come ahead of Chancellor Rachel Reeves' Spring Statement, where she will set out her economic plans.",
       'Reeves to focus on £2bn defence boost in Spring Statement\nChancellor Rachel Reeves is to confirm a £2.2bn increase in defence spending in her Spring Statement, with details of previously announced welfare cuts also to be revealed.\nShe will argue the UK has to "move quickly in a changing world"…',
       'CMA concerned that Ticketmaster may have breached consumer protection law for Oasis reunion tour.',
       "The delay comes after developers warned the tax could hamper the government's housebuilding plans.",
       'Lower Thames Crossing approved by government\nThe largest road tunnel in the UK will be built after an £8.3bn plan was approved by the government.\nThe Lower Thames Crossing would link Tilbury, Essex, and Gravesend in Kent by two tunnels running underneath the River Thames.\nNational Highways hoped…',
       'AI job application rise \'risks hiring incapable staff\'\nA growing use of artificial intelligence (AI) in job applications risks employers hiring candidates who cannot do the work, a business owner has said.\nAdvertising boss James Robinson said he and other business leaders were seeing a "real…',
       "'I could lose £100K despite Woodford redress scheme'\nPeople who lost tens of thousands of pounds when a star stockpicker's investment fund collapsed say they have been let down by the UK's financial regulator and are calling on MPs to investigate.\nAround 300,000 people lost money when Woodford…",
       "Bitcoin in the bush - the crypto mine in remote Zambia\nThe roar of the Zambezi is deafening as millions of gallons of water crash over rocks and tumble down rapids.\nBut there's another sound cutting through the trees of the Zambian bush - the unmistakable high-pitched whine of a bitcoin…",
       'Hyundai unveils $21bn US expansion as Trump tariffs loom\nSouth Korean carmaking giant Hyundai has unveiled $21bn (£16.3bn) of investment in the US.\nThe plan includes a new $5.8bn steel plant in the southern state of Louisiana.\nHyundai also said it will expand its American vehicle production and…',
       'Chinese electric carmaker BYD sales beat Tesla\nChinese electric vehicle maker BYD has reported annual revenue for 2024 that has leapfrogged rival Tesla.\nThe Shenzhen-based firm says revenue rose by 29% to come in at 777 billion yuan ($107bn; £83bn), boosted by sales of its hybrid vehicles. This…',
       "You've requested a page on a website (www.bbc.co.ukundefined) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (www.bbc.co.ukundefined).\nIf you are a visitor of this website:\nPlease try again in a few minutes.\nIf you are the owner of this…",
       "Pizza Hut workers accuse franchisee of docking wages\nPizza Hut workers are accusing a franchise of ''blatantly unlawful'' behaviour alleging it has altered timesheets, docked wages and stopped payments per delivery.\nGlenshire Group which runs all 22 Pizza Hut delivery outlets in Scotland has been…",
       'As the chancellor prepares to update her plans for the economy we hear how ordinary people are tackling their own financial challenges.',
       'Trump threatens tariffs on buyers of Venezuelan oil\nPresident Donald Trump has threatened to impose tariffs of 25% on US imports from countries that purchase oil from Venezuela.\nTrump described the move as a "secondary tariff" aimed at punishing the Latin American country "for numerous reasons",…',
       'Faisal Islam: No tax rises and no return to austerity but will it last?\n"Definitely not a Budget" is the basic message emerging from the Treasury about Wednesday\'s economic statement.\nThere will not just be no red box outside Number 11, there will only be a "thin book" of new policies with a…',
       "Sir Keir Starmer says he is 'deeply concerned' about the closure of Heathrow Airport as a result of a power cut caused by a fire on Friday.",
       'Morrisons to shut 52 cafes and 17 stores\nSupermarket chain Morrisons is to shut 52 cafes and 17 stores putting hundreds of jobs at risk.\nThe retailer will also close a number of in-store services, like the meat and fish counters, pharmacies and its market kitchens at certain sites in an attempt to…',
       'Reeves confirms 15% cut to Civil Service running costs\nGovernment running costs will be cut by 15% by the end of the decade, the chancellor has promised.\nRachel Reeves told the BBC savings would be made from back office and administrative roles rather than front-line services.\nBut unions warned…',
       'DNA testing site 23andMe files for bankruptcy protection\nPopular DNA testing firm 23andMe has filed for bankruptcy protection, and announced that its co-founder and CEO, Anne Wojcicki, has resigned with immediate effect.\nThe company will now attempt to sell itself under the supervision of a…',
       "National Grid confirms Heathrow never lost access to power\nThe chief executive of the National Grid has confirmed power was available to keep Heathrow open throughout Friday's shutdown.\nIn an interview with the Financial Times, John Pettigrew said the fire that knocked out a substation was a…",
       "Disney's Snow White film tops box office despite bad reviews\nDisney's live-action version of the classic fairy-tale Snow White has topped the North American box office chart despite a slew of underwhelming reviews.\nThe movie has taken an estimated $87.3m (£67.5m) globally during its opening…",
       "What makes a rum Jamaican? Question at heart of Caribbean legal dispute\nRum is a key part of Jamaica's cultural identity, but what exactly makes a rum Jamaican?\nThat question is at the centre of a dispute that is continuing to rumble on the Caribbean island, as some producers wish to strengthen…",
       'Councils in England will be asked to publish reports on their repairs or miss out on funding, but critics say long-term thinking is needed.',
       'UK mulls big tech tax changes to avoid US tariffs\nUK taxes on big tech firms may be changed as part of a deal to avoid US President Donald Trump\'s next raft of tariffs, Chancellor Rachel Reeves has suggested.\nShe said talks are "ongoing" about tweaks to the Digital Services Tax (DST), which…',
       'Ed Miliband says there are lessons to be learned after outage led to major flight disruption on Friday.',
       "In an interview with the BBC's Laura Kuenssberg, the chancellor opened up on the public finances and how she's finding the job.",
       'A union says it should instead pay drivers more so they can take time off with their families.',
       'Heathrow substation fire: What went wrong?\nHeathrow Airport was shut down and thousands of homes were left without power on Friday after a fire at a nearby electric supply substation.\nMore than 1,300 flights have been cancelled, passengers are being told not to travel to the airport, and more than…',
       "Heathrow closure: What are my rights?\nHeathrow Airport is closed all day Friday due to a fire at a nearby electrical substation that supplies it with power.\nThe UK's busiest airport has warned of significant disruption over the coming days, with at least 1,300 flights in and out cancelled.\nWhat…",
       "Broadcasters fined £4m for freelance pay collusion\nFour of the UK's biggest sports broadcast and production companies have been fined more than £4m for illegally colluding on freelance pay rates.\nThe UK's competition regulator said the BBC, BT, IMG and ITV must pay a combined £4.24m after being…",
       'Government borrowing higher than expected in February\nUK government borrowing was higher than expected in February, adding pressure to Chancellor Rachel Reeves ahead of her Spring Statement next week.\nBorrowing - the difference between spending and income from taxes - was £10.7bn last month,…',
       "Heathrow Airport will be closed all day Friday due to a fire at a nearby electrical substation that supplies it with power.\nThe UK's busiest airport has warned of significant disruption over the coming days, with at least 1,300 flights in and out cancelled.\nWhat are your rights if your journey has…",
       'Heathrow Airport closes all day over power outage\nHeathrow Airport is closing all day Friday because of a large fire at a nearby electrical substation that supplies it.\nThe airport is experiencing a "significant power outage" because of the fire, a statement from Heathrow said.\n"To maintain the…',
       'Trump uses emergency powers to boost mineral production\nUS President Donald Trump has invoked emergency powers to expand domestic production of critical minerals as he tries to reduce US reliance on imports from countries like China.\nThe executive order, which uses cold war era legislation,…',
       "Tesla vandals face up to 20 years in prison, says attorney general\nUS Attorney General Pam Bondi said Thursday that three defendants accused of vandalism targeting Elon Musk's Tesla electric vehicle company could face up to 20 years in prison.\nBondi said the damage to Tesla cars, dealerships and…",
       'The chatbot has become an "unfiltered and unhinged" digital sensation in India.',
       'TikTokers call for \'chubby filter\' to be banned\nTikTok users have told the BBC they think a viral tool which makes people appear overweight should be banned from the platform.\nKnown as a "chubby filter", the artificial intelligence (AI) tool takes a photo of a person and edits their appearance to…',
       "The slow but steady advance of driverless vehicles\nMike Johns didn't expect his return trip from Los Angeles to Scottsdale, Arizona in December to go viral.\nTo get to the airport he booked a driverless taxi and enjoyed a thrill when he jumped in with curious bystanders looking on.\nBut he got much…",
       'Engineers are building a helicopter that is set to fly itself - without humans operating it remotely.',
       "Tesla makes largest ever Cybertruck recall\nThousands of Tesla Cybertrucks have been recalled in the US due to concerns about part of the electric car's trim falling off in the model's eighth and largest ever recall.\nThe issue affects more than 46,000 trucks made in 2024 and 2025, which analysts…",
       'Family sues Boeing over whistleblower death\nThis story contains details of someone taking their own life, which some readers may find distressing.\nThe family of a Boeing whistleblower who took his own life last year has filed a wrongful death lawsuit against the company.\nThe complaint alleges that…',
       "EU delays plans to retaliate against Trump tariffs\nThe European Union (EU) has delayed plans to hit back at US President Donald Trump's steel and aluminium tariffs until the middle of next month.\nThe trading bloc was set to impose duties on US products, including a 50% levy on whiskey, from 1…",
       'More than a fifth of UK adults still not looking for work\nMore than a fifth of UK working-age adults are still not in work or actively looking for work, official figures suggest.\nThe UK economic inactivity rate was 21.5% in the three months to January, marking a drop from both the previous quarter…',
       "You're hired: Lord Sugar signs up to stay on The Apprentice into his 80s\nLord Sugar has signed a new three-year deal with the BBC to stay on The Apprentice.\nThe billionaire was already contracted to do the 20th series of the show next year, but says he has signed to do three more series, taking…",
       'The company is still valued at more than 100 times its earnings - but it faces problems that experts say go beyond questions around its CEO',
       'Bank of England expected to hold interest rates at 4.5%\nThe Bank of England is expected to keep interest rates on hold when policymakers announce their latest decision on Thursday.\nThe Bank rate heavily influences the cost of borrowing for households, businesses and the government, as well as…',
       'A report by parliament\'s cross-party-transport select committee says accessibility failings are "systematic" across all modes of transport.',
       "Will Trump's tariff war spark big-bang reforms in India?\nIndia has usually turned to economic reforms in times of distress, with the most famous example being 1991, when the country embraced liberalisation in the face of a deep financial crisis.\nNow, with US President Donald Trump's tit-for-tat…",
       "US holds rates steady despite economy fears\nThe US central bank has kept interest rates unchanged for the second time in a row, while warning that economic uncertainty had increased.\nThe decision, which was widely expected, left the Federal Reserve's benchmark interest rate hovering around 4.3%,…",
       "Brewer to increase prices following tax rise\nBritain's oldest brewer has said it will hike its beer prices in response to rising taxes and wage costs taking effect in April.\nShepherd Neame, which is based in Faversham, Kent, and runs 290 pubs primarily in the South East, said the two policies…",
       'Interest rates, set by the Bank of England, affect mortgage, loan and savings rates for millions.',
       "Ben & Jerry's says its boss ousted by Unilever\nBen & Jerry's has said its chief executive, David Stever, was being removed by its parent company, Unilever, in a growing dispute over the ice cream company's political activism.\nThe allegation was part of a legal case filed in a US court by Ben &…",
       'Santander to close 95 branches with 750 jobs at risk\nSantander has announced it is set to close 95 branches across the UK, putting 750 jobs at risk.\nThe High Street bank said its customers were increasingly shifting to banking online and it was aiming to start closing branches from June.\nAs part…'],
      dtype=object)

In [93]:
for (columnName, columnData) in df.items():
    print('Column Name : ', columnName[0])
    print('Column Contents : ', columnData.values)

Column Name :  b
Column Contents :  ['Farage and NatWest settle dispute over bank account closure\nNatWest and Nigel Farage have settled the dispute over the closure of one of his bank accounts.\nThe agreed settlement comes almost two years after the Reform UK leader had his account with Coutts, the prestigious private bank for the…'
 "The UK's economic prospects are better than expected, but the forecasts are precarious and could easily be derailed."
 'Housebuilding plans forecast to boost economy by £6.8bn\nHousebuilding is forecast to hit a 40-year high, with reforms to the planning system expected to boost the economy by £6.8bn, according to the independent spending watchdog.\nThe Office for Budget Responsibility (OBR) said changes including…'
 '23andMe users struggle to delete their highly sensitive data\nThe computer systems of 23andMe have been struggling to cope with the sheer volume of customers racing to delete their data, after the DNA-testing company announced that it was filing for bankruptcy protection.\nThe firm says it has now…'
 'While the Spring Statement focusses on the wider UK economy, it could have implications for your money.'
 "UK growth forecast halved for this year\nThe UK economy is now predicted to grow at a much slower pace this year than previously expected, according to the government's official forecaster.\nPresenting her Spring Statement, Chancellor Rachel Reeves said the Office for Budget Responsibility (OBR)…"
 'Maeve Bradley took action against Citibank after it promoted the person who covered her maternity leave.'
 "Inflation falls to 2.8% ahead of Spring Statement\nUK inflation fell to 2.8% in the year to February, driven by changes to women's clothing prices.\nThe figures come ahead of Chancellor Rachel Reeves' Spring Statement, where she will set out her economic plans."
 'Reeves to focus on £2bn defence boost in Spring Statement\nChancellor Rachel Reeves is to confirm a £2.2bn increase in defence spending in her Spring Statement, with details of previously announced welfare cuts also to be revealed.\nShe will argue the UK has to "move quickly in a changing world"…'
 'CMA concerned that Ticketmaster may have breached consumer protection law for Oasis reunion tour.'
 "The delay comes after developers warned the tax could hamper the government's housebuilding plans."
 'Lower Thames Crossing approved by government\nThe largest road tunnel in the UK will be built after an £8.3bn plan was approved by the government.\nThe Lower Thames Crossing would link Tilbury, Essex, and Gravesend in Kent by two tunnels running underneath the River Thames.\nNational Highways hoped…'
 'AI job application rise \'risks hiring incapable staff\'\nA growing use of artificial intelligence (AI) in job applications risks employers hiring candidates who cannot do the work, a business owner has said.\nAdvertising boss James Robinson said he and other business leaders were seeing a "real…'
 "'I could lose £100K despite Woodford redress scheme'\nPeople who lost tens of thousands of pounds when a star stockpicker's investment fund collapsed say they have been let down by the UK's financial regulator and are calling on MPs to investigate.\nAround 300,000 people lost money when Woodford…"
 "Bitcoin in the bush - the crypto mine in remote Zambia\nThe roar of the Zambezi is deafening as millions of gallons of water crash over rocks and tumble down rapids.\nBut there's another sound cutting through the trees of the Zambian bush - the unmistakable high-pitched whine of a bitcoin…"
 'Hyundai unveils $21bn US expansion as Trump tariffs loom\nSouth Korean carmaking giant Hyundai has unveiled $21bn (£16.3bn) of investment in the US.\nThe plan includes a new $5.8bn steel plant in the southern state of Louisiana.\nHyundai also said it will expand its American vehicle production and…'
 'Chinese electric carmaker BYD sales beat Tesla\nChinese electric vehicle maker BYD has reported annual revenue for 2024 that has leapfrogged rival Tesla.\nThe Shenzhen-based firm says revenue rose by 29% to come in at 777 billion yuan ($107bn; £83bn), boosted by sales of its hybrid vehicles. This…'
 "You've requested a page on a website (www.bbc.co.ukundefined) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (www.bbc.co.ukundefined).\nIf you are a visitor of this website:\nPlease try again in a few minutes.\nIf you are the owner of this…"
 "Pizza Hut workers accuse franchisee of docking wages\nPizza Hut workers are accusing a franchise of ''blatantly unlawful'' behaviour alleging it has altered timesheets, docked wages and stopped payments per delivery.\nGlenshire Group which runs all 22 Pizza Hut delivery outlets in Scotland has been…"
 'As the chancellor prepares to update her plans for the economy we hear how ordinary people are tackling their own financial challenges.'
 'Trump threatens tariffs on buyers of Venezuelan oil\nPresident Donald Trump has threatened to impose tariffs of 25% on US imports from countries that purchase oil from Venezuela.\nTrump described the move as a "secondary tariff" aimed at punishing the Latin American country "for numerous reasons",…'
 'Faisal Islam: No tax rises and no return to austerity but will it last?\n"Definitely not a Budget" is the basic message emerging from the Treasury about Wednesday\'s economic statement.\nThere will not just be no red box outside Number 11, there will only be a "thin book" of new policies with a…'
 "Sir Keir Starmer says he is 'deeply concerned' about the closure of Heathrow Airport as a result of a power cut caused by a fire on Friday."
 'Morrisons to shut 52 cafes and 17 stores\nSupermarket chain Morrisons is to shut 52 cafes and 17 stores putting hundreds of jobs at risk.\nThe retailer will also close a number of in-store services, like the meat and fish counters, pharmacies and its market kitchens at certain sites in an attempt to…'
 'Reeves confirms 15% cut to Civil Service running costs\nGovernment running costs will be cut by 15% by the end of the decade, the chancellor has promised.\nRachel Reeves told the BBC savings would be made from back office and administrative roles rather than front-line services.\nBut unions warned…'
 'DNA testing site 23andMe files for bankruptcy protection\nPopular DNA testing firm 23andMe has filed for bankruptcy protection, and announced that its co-founder and CEO, Anne Wojcicki, has resigned with immediate effect.\nThe company will now attempt to sell itself under the supervision of a…'
 "National Grid confirms Heathrow never lost access to power\nThe chief executive of the National Grid has confirmed power was available to keep Heathrow open throughout Friday's shutdown.\nIn an interview with the Financial Times, John Pettigrew said the fire that knocked out a substation was a…"
 "Disney's Snow White film tops box office despite bad reviews\nDisney's live-action version of the classic fairy-tale Snow White has topped the North American box office chart despite a slew of underwhelming reviews.\nThe movie has taken an estimated $87.3m (£67.5m) globally during its opening…"
 "What makes a rum Jamaican? Question at heart of Caribbean legal dispute\nRum is a key part of Jamaica's cultural identity, but what exactly makes a rum Jamaican?\nThat question is at the centre of a dispute that is continuing to rumble on the Caribbean island, as some producers wish to strengthen…"
 'Councils in England will be asked to publish reports on their repairs or miss out on funding, but critics say long-term thinking is needed.'
 'UK mulls big tech tax changes to avoid US tariffs\nUK taxes on big tech firms may be changed as part of a deal to avoid US President Donald Trump\'s next raft of tariffs, Chancellor Rachel Reeves has suggested.\nShe said talks are "ongoing" about tweaks to the Digital Services Tax (DST), which…'
 'Ed Miliband says there are lessons to be learned after outage led to major flight disruption on Friday.'
 "In an interview with the BBC's Laura Kuenssberg, the chancellor opened up on the public finances and how she's finding the job."
 'A union says it should instead pay drivers more so they can take time off with their families.'
 'Heathrow substation fire: What went wrong?\nHeathrow Airport was shut down and thousands of homes were left without power on Friday after a fire at a nearby electric supply substation.\nMore than 1,300 flights have been cancelled, passengers are being told not to travel to the airport, and more than…'
 "Heathrow closure: What are my rights?\nHeathrow Airport is closed all day Friday due to a fire at a nearby electrical substation that supplies it with power.\nThe UK's busiest airport has warned of significant disruption over the coming days, with at least 1,300 flights in and out cancelled.\nWhat…"
 "Broadcasters fined £4m for freelance pay collusion\nFour of the UK's biggest sports broadcast and production companies have been fined more than £4m for illegally colluding on freelance pay rates.\nThe UK's competition regulator said the BBC, BT, IMG and ITV must pay a combined £4.24m after being…"
 'Government borrowing higher than expected in February\nUK government borrowing was higher than expected in February, adding pressure to Chancellor Rachel Reeves ahead of her Spring Statement next week.\nBorrowing - the difference between spending and income from taxes - was £10.7bn last month,…'
 "Heathrow Airport will be closed all day Friday due to a fire at a nearby electrical substation that supplies it with power.\nThe UK's busiest airport has warned of significant disruption over the coming days, with at least 1,300 flights in and out cancelled.\nWhat are your rights if your journey has…"
 'Heathrow Airport closes all day over power outage\nHeathrow Airport is closing all day Friday because of a large fire at a nearby electrical substation that supplies it.\nThe airport is experiencing a "significant power outage" because of the fire, a statement from Heathrow said.\n"To maintain the…'
 'Trump uses emergency powers to boost mineral production\nUS President Donald Trump has invoked emergency powers to expand domestic production of critical minerals as he tries to reduce US reliance on imports from countries like China.\nThe executive order, which uses cold war era legislation,…'
 "Tesla vandals face up to 20 years in prison, says attorney general\nUS Attorney General Pam Bondi said Thursday that three defendants accused of vandalism targeting Elon Musk's Tesla electric vehicle company could face up to 20 years in prison.\nBondi said the damage to Tesla cars, dealerships and…"
 'The chatbot has become an "unfiltered and unhinged" digital sensation in India.'
 'TikTokers call for \'chubby filter\' to be banned\nTikTok users have told the BBC they think a viral tool which makes people appear overweight should be banned from the platform.\nKnown as a "chubby filter", the artificial intelligence (AI) tool takes a photo of a person and edits their appearance to…'
 "The slow but steady advance of driverless vehicles\nMike Johns didn't expect his return trip from Los Angeles to Scottsdale, Arizona in December to go viral.\nTo get to the airport he booked a driverless taxi and enjoyed a thrill when he jumped in with curious bystanders looking on.\nBut he got much…"
 'Engineers are building a helicopter that is set to fly itself - without humans operating it remotely.'
 "Tesla makes largest ever Cybertruck recall\nThousands of Tesla Cybertrucks have been recalled in the US due to concerns about part of the electric car's trim falling off in the model's eighth and largest ever recall.\nThe issue affects more than 46,000 trucks made in 2024 and 2025, which analysts…"
 'Family sues Boeing over whistleblower death\nThis story contains details of someone taking their own life, which some readers may find distressing.\nThe family of a Boeing whistleblower who took his own life last year has filed a wrongful death lawsuit against the company.\nThe complaint alleges that…'
 "EU delays plans to retaliate against Trump tariffs\nThe European Union (EU) has delayed plans to hit back at US President Donald Trump's steel and aluminium tariffs until the middle of next month.\nThe trading bloc was set to impose duties on US products, including a 50% levy on whiskey, from 1…"
 'More than a fifth of UK adults still not looking for work\nMore than a fifth of UK working-age adults are still not in work or actively looking for work, official figures suggest.\nThe UK economic inactivity rate was 21.5% in the three months to January, marking a drop from both the previous quarter…'
 "You're hired: Lord Sugar signs up to stay on The Apprentice into his 80s\nLord Sugar has signed a new three-year deal with the BBC to stay on The Apprentice.\nThe billionaire was already contracted to do the 20th series of the show next year, but says he has signed to do three more series, taking…"
 'The company is still valued at more than 100 times its earnings - but it faces problems that experts say go beyond questions around its CEO'
 'Bank of England expected to hold interest rates at 4.5%\nThe Bank of England is expected to keep interest rates on hold when policymakers announce their latest decision on Thursday.\nThe Bank rate heavily influences the cost of borrowing for households, businesses and the government, as well as…'
 'A report by parliament\'s cross-party-transport select committee says accessibility failings are "systematic" across all modes of transport.'
 "Will Trump's tariff war spark big-bang reforms in India?\nIndia has usually turned to economic reforms in times of distress, with the most famous example being 1991, when the country embraced liberalisation in the face of a deep financial crisis.\nNow, with US President Donald Trump's tit-for-tat…"
 "US holds rates steady despite economy fears\nThe US central bank has kept interest rates unchanged for the second time in a row, while warning that economic uncertainty had increased.\nThe decision, which was widely expected, left the Federal Reserve's benchmark interest rate hovering around 4.3%,…"
 "Brewer to increase prices following tax rise\nBritain's oldest brewer has said it will hike its beer prices in response to rising taxes and wage costs taking effect in April.\nShepherd Neame, which is based in Faversham, Kent, and runs 290 pubs primarily in the South East, said the two policies…"
 'Interest rates, set by the Bank of England, affect mortgage, loan and savings rates for millions.'
 "Ben & Jerry's says its boss ousted by Unilever\nBen & Jerry's has said its chief executive, David Stever, was being removed by its parent company, Unilever, in a growing dispute over the ice cream company's political activism.\nThe allegation was part of a legal case filed in a US court by Ben &…"
 'Santander to close 95 branches with 750 jobs at risk\nSantander has announced it is set to close 95 branches across the UK, putting 750 jobs at risk.\nThe High Street bank said its customers were increasingly shifting to banking online and it was aiming to start closing branches from June.\nAs part…']
Column Name :  i
Column Contents :  [{'s': 'https://cdn.biztoc.com/058954c045492a73_s.webp', 'sq': 'https://cdn.biztoc.com/058954c045492a73_sq.webp'}
 {'s': 'https://cdn.biztoc.com/ab948b10b82131bf_s.webp', 'sq': 'https://cdn.biztoc.com/ab948b10b82131bf_sq.webp'}
 {'s': 'https://cdn.biztoc.com/e0e56e6a6c714085_s.webp', 'sq': 'https://cdn.biztoc.com/e0e56e6a6c714085_sq.webp'}
 {'s': 'https://cdn.biztoc.com/499acb3b38545a44_s.webp', 'sq': 'https://cdn.biztoc.com/499acb3b38545a44_sq.webp'}
 {'s': 'https://cdn.biztoc.com/4e8e6b59bd0760f9_s.webp', 'sq': 'https://cdn.biztoc.com/4e8e6b59bd0760f9_sq.webp'}
 {'s': 'https://cdn.biztoc.com/45d65104d0616e5b_s.webp', 'sq': 'https://cdn.biztoc.com/45d65104d0616e5b_sq.webp'}
 {'s': 'https://cdn.biztoc.com/4f1e70199b1315c3_s.webp', 'sq': 'https://cdn.biztoc.com/4f1e70199b1315c3_sq.webp'}
 {'s': 'https://cdn.biztoc.com/28f5d43595442dd9_s.webp', 'sq': 'https://cdn.biztoc.com/28f5d43595442dd9_sq.webp'}
 {'s': 'https://cdn.biztoc.com/b58a23702216a5f6_s.webp', 'sq': 'https://cdn.biztoc.com/b58a23702216a5f6_sq.webp'}
 {'s': 'https://cdn.biztoc.com/73e1932181f49674_s.webp', 'sq': 'https://cdn.biztoc.com/73e1932181f49674_sq.webp'}
 {'s': 'https://cdn.biztoc.com/29067bfa516d85e5_s.webp', 'sq': 'https://cdn.biztoc.com/29067bfa516d85e5_sq.webp'}
 {'s': 'https://cdn.biztoc.com/64952168afdc8443_s.webp', 'sq': 'https://cdn.biztoc.com/64952168afdc8443_sq.webp'}
 {'s': 'https://cdn.biztoc.com/1485b5225ad9b611_s.webp', 'sq': 'https://cdn.biztoc.com/1485b5225ad9b611_sq.webp'}
 {'s': 'https://cdn.biztoc.com/29997895f5f9c92c_s.webp', 'sq': 'https://cdn.biztoc.com/29997895f5f9c92c_sq.webp'}
 {'s': 'https://cdn.biztoc.com/ec6d9b98fc373087_s.webp', 'sq': 'https://cdn.biztoc.com/ec6d9b98fc373087_sq.webp'}
 {'s': 'https://cdn.biztoc.com/483f0f0f4595aaef_s.webp', 'sq': 'https://cdn.biztoc.com/483f0f0f4595aaef_sq.webp'}
 {'s': 'https://cdn.biztoc.com/c5bcccf298f20868_s.webp', 'sq': 'https://cdn.biztoc.com/c5bcccf298f20868_sq.webp'}
 {'s': 'https://cdn.biztoc.com/43187929f577ea4f_s.webp', 'sq': 'https://cdn.biztoc.com/43187929f577ea4f_sq.webp'}
 {'s': 'https://cdn.biztoc.com/1ca0528ce353f00d_s.webp', 'sq': 'https://cdn.biztoc.com/1ca0528ce353f00d_sq.webp'}
 {'s': 'https://cdn.biztoc.com/5cfdb1e49606e29a_s.webp', 'sq': 'https://cdn.biztoc.com/5cfdb1e49606e29a_sq.webp'}
 {'s': 'https://cdn.biztoc.com/207c5d3516491bb3_s.webp', 'sq': 'https://cdn.biztoc.com/207c5d3516491bb3_sq.webp'}
 {'s': 'https://cdn.biztoc.com/57ebb7f3a292730c_s.webp', 'sq': 'https://cdn.biztoc.com/57ebb7f3a292730c_sq.webp'}
 {'s': 'https://cdn.biztoc.com/d0824f10926cdaee_s.webp', 'sq': 'https://cdn.biztoc.com/d0824f10926cdaee_sq.webp'}
 {'s': 'https://cdn.biztoc.com/3bfff465ea9f7e4f_s.webp', 'sq': 'https://cdn.biztoc.com/3bfff465ea9f7e4f_sq.webp'}
 {'s': 'https://cdn.biztoc.com/89f422fe424dc374_s.webp', 'sq': 'https://cdn.biztoc.com/89f422fe424dc374_sq.webp'}
 {'s': 'https://cdn.biztoc.com/33542b4096b54007_s.webp', 'sq': 'https://cdn.biztoc.com/33542b4096b54007_sq.webp'}
 {'s': 'https://cdn.biztoc.com/915211d68dce4029_s.webp', 'sq': 'https://cdn.biztoc.com/915211d68dce4029_sq.webp'}
 {'s': 'https://cdn.biztoc.com/1feeec981f1229c1_s.webp', 'sq': 'https://cdn.biztoc.com/1feeec981f1229c1_sq.webp'}
 {'s': 'https://cdn.biztoc.com/8487cbdf4b9970b0_s.webp', 'sq': 'https://cdn.biztoc.com/8487cbdf4b9970b0_sq.webp'}
 {'s': 'https://cdn.biztoc.com/9c4c95e78afc3f5d_s.webp', 'sq': 'https://cdn.biztoc.com/9c4c95e78afc3f5d_sq.webp'}
 {'s': 'https://cdn.biztoc.com/b42d2cb30b8a8d56_s.webp', 'sq': 'https://cdn.biztoc.com/b42d2cb30b8a8d56_sq.webp'}
 {'s': 'https://cdn.biztoc.com/c04f7fa9ebbc1e15_s.webp', 'sq': 'https://cdn.biztoc.com/c04f7fa9ebbc1e15_sq.webp'}
 {'s': 'https://cdn.biztoc.com/54ca418fc26c24c2_s.webp', 'sq': 'https://cdn.biztoc.com/54ca418fc26c24c2_sq.webp'}
 {'s': 'https://cdn.biztoc.com/b3e9b93393f1ada3_s.webp', 'sq': 'https://cdn.biztoc.com/b3e9b93393f1ada3_sq.webp'}
 {'s': 'https://cdn.biztoc.com/7db2e66c6a990008_s.webp', 'sq': 'https://cdn.biztoc.com/7db2e66c6a990008_sq.webp'}
 {'s': 'https://cdn.biztoc.com/90a5082a1e7791f6_s.webp', 'sq': 'https://cdn.biztoc.com/90a5082a1e7791f6_sq.webp'}
 {'s': 'https://cdn.biztoc.com/ce6905775d598374_s.webp', 'sq': 'https://cdn.biztoc.com/ce6905775d598374_sq.webp'}
 {'s': 'https://cdn.biztoc.com/23a4cfc4f6b226bc_s.webp', 'sq': 'https://cdn.biztoc.com/23a4cfc4f6b226bc_sq.webp'}
 {'s': 'https://cdn.biztoc.com/82ff2f0d80089de5_s.webp', 'sq': 'https://cdn.biztoc.com/82ff2f0d80089de5_sq.webp'}
 {'s': 'https://cdn.biztoc.com/391b66f483d1b895_s.webp', 'sq': 'https://cdn.biztoc.com/391b66f483d1b895_sq.webp'}
 {'s': 'https://cdn.biztoc.com/6c8f847943ea1938_s.webp', 'sq': 'https://cdn.biztoc.com/6c8f847943ea1938_sq.webp'}
 {'s': 'https://cdn.biztoc.com/5b175fce2a7bd36e_s.webp', 'sq': 'https://cdn.biztoc.com/5b175fce2a7bd36e_sq.webp'}

In [94]:
df['title'].values

array(['Farage and NatWest settle dispute over bank account closure',
       'Faisal Islam: Reeves is in danger of being boxed in by her own rules',
       'Housebuilding plans forecast to boost economy by £6.8bn',
       '23andMe users struggle to delete their highly sensitive data',
       'Three ways the Spring Statement could affect you and your money',
       'UK growth forecast halved for this year',
       'Maternity discrimination case settled for £215k',
       'Inflation falls to 2.8% ahead of Spring Statement',
       'Reeves to focus on £2bn defence boost in Spring Statement',
       "Oasis sale 'may have misled fans' says watchdog",
       'Cladding tax on new homes delayed for a year',
       'Lower Thames Crossing approved by government',
       "AI job application rise 'risks hiring incapable staff'",
       "'I could lose £100K despite Woodford redress scheme'",
       'Bitcoin in the bush - the crypto mine in remote Zambia',
       'Hyundai unveils $21bn US expansion as Trump tariffs loom',
       'Chinese electric carmaker BYD sales beat Tesla',
       'Bitcoin in the bush - the crypto mine in remote Zambia',
       'Pizza Hut workers accuse franchisee of docking wages',
       "'I'll make £12.24 an hour - I live payday to payday'",
       'Trump threatens tariffs on buyers of Venezuelan oil',
       'Faisal Islam: No tax rises and no return to austerity but will it last?',
       'Heathrow closure deeply concerning, says PM',
       'Morrisons to shut 52 cafes and 17 stores',
       'Reeves confirms 15% cut to Civil Service running costs',
       'DNA testing site 23andMe files for bankruptcy protection',
       'National Grid confirms Heathrow never lost access to power',
       "Disney's Snow White film tops box office despite bad reviews",
       'What makes a rum Jamaican? Question at heart of Caribbean legal dispute',
       "Sort 'pothole plague' or lose cash, councils warned",
       'UK mulls big tech tax changes to avoid US tariffs',
       'Investigation ordered into power outage that closed Heathrow',
       "Rachel Reeves: I will not 'tax and spend'",
       'Uber offers 20 hours of free childcare in bid to lure female drivers',
       'Heathrow substation fire: What went wrong?',
       'Heathrow closure: What are my rights?',
       'Broadcasters fined £4m for freelance pay collusion',
       'Government borrowing higher than expected as pressure builds on Reeves',
       'What are my rights if my flight is cancelled or delayed?',
       'Heathrow Airport closes all day over power outage',
       'Trump uses emergency powers to boost mineral production',
       'Tesla vandals face up to 20 years in prison, says attorney general',
       "Why Elon Musk's Grok is kicking up a storm in India",
       "TikTokers call for 'chubby filter' to be banned",
       'The slow but steady advance of driverless vehicles',
       "Engineers building 'helicopter that flies itself'",
       'Tesla makes largest ever Cybertruck recall',
       'Family sues Boeing over whistleblower death',
       'EU delays plans to retaliate against Trump tariffs',
       'More than a fifth of UK adults still not looking for work',
       "You're hired: Lord Sugar signs up to stay on The Apprentice into his 80s",
       "Tesla's challenges run deeper than 'toxic' controversy around Elon Musk",
       'Bank of England expected to hold interest rates at 4.5%',
       "Disabled travel access an 'embarrassment', MPs say",
       "Will Trump's tariff war spark big-bang reforms in India?",
       'US holds rates steady despite economy fears',
       'Brewer to increase prices following tax rise',
       'When will interest rates go down again?',
       "Ben & Jerry's says its boss ousted by Unilever",
       'Santander to close 95 branches with 750 jobs at risk'],
      dtype=object)

In [95]:
import spacy


spacy.cli.download("en_core_web_sm")
nlp = spacy.load("en_core_web_sm")


def is_company_spacy(text):
    doc = nlp(text)
    for ent in doc.ents:
        if ent.label_ == "ORG":  # Organization entity
            return True
    return False

# Test Cases
print(is_company_spacy("Microsoft Corporation"))  # True
print(is_company_spacy("Elon Musk"))             # False

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
True
False

In [96]:
for i in df['title'].values:
  print(is_company_spacy(i))

True
False
False
False
False
False
False
True
False
False
False
True
False
True
False
True
True
False
True
False
False
False
False
False
True
False
False
True
False
False
False
False
False
False
False
False
False
False
False
False
True
False
False
True
False
False
True
True
True
False
True
True
True
False
False
False
False
False
True
False

In [97]:
for x in range(len(df['body'].values)):
  print(is_company_spacy(df['body'].values[x]))

True
False
True
False
True
True
True
True
False
True
False
True
False
True
False
True
True
True
True
False
False
True
False
True
True
False
True
True
False
False
True
False
True
False
False
False
True
False
False
True
True
False
False
True
False
False
True
True
True
False
True
False
True
False
False
True
False
True
True
False

In [98]:
df = df[df.apply(lambda row: is_company_spacy(row["title"]) or is_company_spacy(row["body"]), axis=1)]
df

,body,img,published,title,url
0,Farage and NatWest settle dispute over bank ac...,{'s': 'https://cdn.biztoc.com/058954c045492a73...,"Wed, 26 Mar 2025 19:19:52 GMT",Farage and NatWest settle dispute over bank ac...,https://www.bbc.com/news/articles/czx79161e2wo...
2,Housebuilding plans forecast to boost economy ...,{'s': 'https://cdn.biztoc.com/e0e56e6a6c714085...,"Wed, 26 Mar 2025 16:15:45 GMT",Housebuilding plans forecast to boost economy ...,https://www.bbc.com/news/articles/cy4vj7yk0nyo...
4,While the Spring Statement focusses on the wid...,{'s': 'https://cdn.biztoc.com/4e8e6b59bd0760f9...,"Wed, 26 Mar 2025 14:42:13 GMT",Three ways the Spring Statement could affect y...,https://www.bbc.com/news/articles/cvged1en8jro...
5,UK growth forecast halved for this year\nThe U...,{'s': 'https://cdn.biztoc.com/45d65104d0616e5b...,"Wed, 26 Mar 2025 13:11:05 GMT",UK growth forecast halved for this year,https://www.bbc.com/news/articles/cqjd5rklyrko...
6,Maeve Bradley took action against Citibank aft...,{'s': 'https://cdn.biztoc.com/4f1e70199b1315c3...,"Wed, 26 Mar 2025 00:24:14 GMT",Maternity discrimination case settled for £215k,https://www.bbc.com/news/articles/cvgp0j3jjnmo...
7,Inflation falls to 2.8% ahead of Spring Statem...,{'s': 'https://cdn.biztoc.com/28f5d43595442dd9...,"Wed, 26 Mar 2025 07:17:32 GMT",Inflation falls to 2.8% ahead of Spring Statement,https://www.bbc.com/news/articles/cx2g3wwk01vo...
9,CMA concerned that Ticketmaster may have breac...,{'s': 'https://cdn.biztoc.com/73e1932181f49674...,"Tue, 25 Mar 2025 13:29:03 GMT",Oasis sale 'may have misled fans' says watchdog,https://www.bbc.com/news/articles/cddy85n57j8o...
11,Lower Thames Crossing approved by government\n...,{'s': 'https://cdn.biztoc.com/64952168afdc8443...,"Tue, 25 Mar 2025 10:41:08 GMT",Lower Thames Crossing approved by government,https://www.bbc.com/news/articles/crewy5472gxo...
13,'I could lose £100K despite Woodford redress s...,{'s': 'https://cdn.biztoc.com/29997895f5f9c92c...,"Tue, 25 Mar 2025 00:49:47 GMT",'I could lose £100K despite Woodford redress s...,https://www.bbc.com/news/articles/cx2gw5y8er7o...
15,Hyundai unveils $21bn US expansion as Trump ta...,{'s': 'https://cdn.biztoc.com/483f0f0f4595aaef...,"Tue, 25 Mar 2025 04:52:13 GMT",Hyundai unveils $21bn US expansion as Trump ta...,https://www.bbc.com/news/articles/cgkmvdz144vo...
16,Chinese electric carmaker BYD sales beat Tesla...,{'s': 'https://cdn.biztoc.com/c5bcccf298f20868...,"Tue, 25 Mar 2025 03:24:09 GMT",Chinese electric carmaker BYD sales beat Tesla,https://www.bbc.com/news/articles/cd65d583qvzo...
17,You've requested a page on a website (www.bbc....,{'s': 'https://cdn.biztoc.com/43187929f577ea4f...,"Tue, 25 Mar 2025 00:06:48 GMT",Bitcoin in the bush - the crypto mine in remot...,https://www.bbc.co.ukundefined/?ref=biztoc.com
18,Pizza Hut workers accuse franchisee of docking...,{'s': 'https://cdn.biztoc.com/1ca0528ce353f00d...,"Tue, 25 Mar 2025 00:02:01 GMT",Pizza Hut workers accuse franchisee of docking...,https://www.bbc.com/news/articles/c3w10qnnjvyo...
21,Faisal Islam: No tax rises and no return to au...,{'s': 'https://cdn.biztoc.com/57ebb7f3a292730c...,"Mon, 24 Mar 2025 16:19:53 GMT",Faisal Islam: No tax rises and no return to au...,https://www.bbc.com/news/articles/c1kjxkkn3mzo...
23,Morrisons to shut 52 cafes and 17 stores\nSupe...,{'s': 'https://cdn.biztoc.com/3bfff465ea9f7e4f...,"Mon, 24 Mar 2025 12:54:48 GMT",Morrisons to shut 52 cafes and 17 stores,https://www.bbc.com/news/articles/cqx0v5xprz4o...
24,Reeves confirms 15% cut to Civil Service runni...,{'s': 'https://cdn.biztoc.com/89f422fe424dc374...,"Sun, 23 Mar 2025 11:33:31 GMT",Reeves confirms 15% cut to Civil Service runni...,https://www.bbc.com/news/articles/cy5nzy403l0o...
26,National Grid confirms Heathrow never lost acc...,{'s': 'https://cdn.biztoc.com/915211d68dce4029...,"Mon, 24 Mar 2025 03:51:35 GMT",National Grid confirms Heathrow never lost acc...,https://www.bbc.com/news/articles/cdjy4m0n1exo...
27,Disney's Snow White film tops box office despi...,{'s': 'https://cdn.biztoc.com/1feeec981f1229c1...,"Mon, 24 Mar 2025 02:58:23 GMT",Disney's Snow White film tops box office despi...,https://www.bbc.com/news/articles/c74ke77v7rvo...
30,UK mulls big tech tax changes to avoid US tari...,{'s': 'https://cdn.biztoc.com/b42d2cb30b8a8d56...,"Sun, 23 Mar 2025 12:02:08 GMT",UK mulls big tech tax changes to avoid US tariffs,https://www.bbc.com/news/articles/c8j0dgym8w1o...
32,In an interview with the BBC's Laura Kuenssber...,{'s': 'https://cdn.biztoc.com/54ca418fc26c24c2...,"Sat, 22 Mar 2025 05:46:59 GMT",Rachel Reeves: I will not 'tax and spend',https://www.bbc.com/news/articles/c78eg7dp9ypo...
36,Broadcasters fined £4m for freelance pay collu...,{'s': 'https://cdn.biztoc.com/ce6905775d598374...,"Fri, 21 Mar 2025 10:45:58 GMT",Broadcasters fined £4m for freelance pay collu...,https://www.bbc.com/news/articles/ce34q1792d0o...
39,Heathrow Airport closes all day over power out...,{'s': 'https://cdn.biztoc.com/391b66f483d1b895...,"Fri, 21 Mar 2025 03:32:18 GMT",Heathrow Airport closes all day over power outage,https://www.bbc.com/news/articles/cvg5dg4p2l0o...
40,Trump uses emergency powers to boost mineral p...,{'s': 'https://cdn.biztoc.com/6c8f847943ea1938...,"Fri, 21 Mar 2025 03:29:37 GMT",Trump uses emergency powers to boost mineral p...,https://www.bbc.com/news/articles/cwye089j1zdo...
43,TikTokers call for 'chubby filter' to be banne...,{'s': 'https://cdn.biztoc.com/bfbf4692cfa0b907...,"Fri, 21 Mar 2025 00:02:37 GMT",TikTokers call for 'chubby filter' to be banned,https://www.bbc.com/news/articles/c4gmvjvv6vjo...
46,Tesla makes largest ever Cybertruck recall\nTh...,{'s': 'https://cdn.biztoc.com/58460be1ca706ec3...,"Thu, 20 Mar 2025 18:47:55 GMT",Tesla makes largest ever Cybertruck recall,https://www.bbc.com/news/articles/c0kgy20x0x4o...
47,Family sues Boeing over whistleblower death\nT...,{'s': 'https://cdn.biztoc.com/cbab1c886f7607f0...,"Thu, 20 Mar 2025 16:24:49 GMT",Family sues Boeing over whistleblower death,https://www.bbc.com/news/articles/cwyje8e8rdlo...
48,EU delays plans to retaliate against Trump tar...,{'s': 'https://cdn.biztoc.com/1ef719daee2a2290...,"Thu, 20 Mar 2025 16:10:19 GMT",EU delays plans to retaliate against Trump tar...,https://www.bbc.com/news/articles/c62z157jvd8o...
50,You're hired: Lord Sugar signs up to stay on T...,{'s': 'https://cdn.biztoc.com/607b8be6e9bbb280...,"Thu, 20 Mar 2025 01:45:51 GMT",You're hired: Lord Sugar signs up to stay on T...,https://www.bbc.com/news/articles/c20d8jlnkk8o...
51,The company is still valued at more than 100 t...,{'s': 'https://cdn.biztoc.com/7c9fe0a9425bcf84...,"Thu, 20 Mar 2025 00:05:40 GMT",Tesla's challenges run deeper than 'toxic' con...,https://www.bbc.com/news/articles/cz61vwjel2zo...
52,Bank of England expected to hold interest rate...,{'s': 'https://cdn.biztoc.com/44d44f3973cf5206...,"Thu, 20 Mar 2025 00:06:51 GMT",Bank of England expected to hold interest rate...,https://www.bbc.com/news/articles/ckgz82838l8o...
55,US holds rates steady despite economy fears\nT...,{'s': 'https://cdn.biztoc.com/363289c0ff0ffe3f...,"Wed, 19 Mar 2025 18:35:30 GMT",US holds rates steady despite economy fears,https://www.bbc.com/news/articles/cvgp574lvdxo...
57,"Interest rates, set by the Bank of England, af...",{'s': 'https://cdn.biztoc.com/f6c4b4b6a65f0132...,"Wed, 19 Mar 2025 11:46:19 GMT",When will interest rates go down again?,https://www.bbc.co.uk/news/business-57764601?r...
58,Ben & Jerry's says its boss ousted by Unilever...,{'s': 'https://cdn.biztoc.com/d7c4e44caebc9e2a...,"Wed, 19 Mar 2025 08:53:50 GMT",Ben & Jerry's says its boss ousted by Unilever,https://www.bbc.com/news/articles/ckg8pk9rpx4o...

In [99]:
spacy.cli.download("en_core_web_sm")
nlp = spacy.load("en_core_web_sm")

def extract_company(text):
    doc = nlp(text)
    companies = [ent.text for ent in doc.ents if ent.label_ == "ORG"]
    return companies if companies else None

# Test Cases
text1 = "I recently applied for a job at Google and Amazon."
text2 = "John is working at Tesla Inc and loves it."
text3 = "I enjoy hiking on weekends."

print(extract_company(text1))  # ['Google', 'Amazon']
print(extract_company(text2))  # ['Tesla Inc']
print(extract_company(text3))  # None

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
['Google', 'Amazon']
['Tesla Inc']
None

In [100]:
for i in df['title'].values:
  print(extract_company(i))

['NatWest']
None
None
None
None
['Spring Statement']
None
['Lower Thames Crossing']
['Woodford']
['Hyundai', 'Trump']
['BYD', 'Tesla']
None
['Pizza Hut']
None
None
['Civil Service']
None
['Disney']
None
None
None
None
['Trump']
['TikTokers']
['Tesla']
['Boeing']
['EU', 'Trump']
['Apprentice']
['Tesla']
['Bank of England']
None
None
["Ben & Jerry's", 'Unilever']

In [101]:
for x in range(len(df['body'].values)):
  print(extract_company(df['body'].values[x]))

['NatWest', 'NatWest', 'Reform']
['The Office for Budget Responsibility', 'OBR']
['Spring Statement']
['the Office for Budget Responsibility', 'OBR']
['Citibank']
['Spring Statement\nUK']
['CMA']
['Lower Thames Crossing', 'The Lower Thames Crossing']
['Woodford', 'Woodford']
['Hyundai', 'Trump', 'Hyundai', 'Hyundai']
['BYD', 'BYD']
['Cloudflare', 'Cloudflare']
['Pizza Hut', 'Pizza Hut', 'Glenshire Group', 'Pizza Hut']
['Budget', 'Treasury']
['Supermarket']
['Civil Service', 'BBC']
['the National Grid', 'the Financial Times']
['Disney', 'Disney']
['Digital Services Tax', 'DST']
['BBC']
['BBC', 'IMG', 'ITV']
['Heathrow']
['Trump']
['TikTokers', 'TikTok', 'BBC']
['Tesla', 'Tesla Cybertrucks']
['Boeing', 'Boeing']
['EU', 'Trump', 'The European Union', 'EU']
['Apprentice', 'BBC', 'Apprentice']
None
['Bank of England', 'The Bank of England', 'Bank']
["the Federal Reserve's"]
['the Bank of England']
["Ben & Jerry's", "Unilever\nBen & Jerry's", 'Unilever', 'Ben &']

In [102]:
df["companies_mentioned"] = df["body"].apply(extract_company)
df

<ipython-input-102-b99a91b7baa8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["companies_mentioned"] = df["body"].apply(extract_company)

,body,img,published,title,url,companies_mentioned
0,Farage and NatWest settle dispute over bank ac...,{'s': 'https://cdn.biztoc.com/058954c045492a73...,"Wed, 26 Mar 2025 19:19:52 GMT",Farage and NatWest settle dispute over bank ac...,https://www.bbc.com/news/articles/czx79161e2wo...,"[NatWest, NatWest, Reform]"
2,Housebuilding plans forecast to boost economy ...,{'s': 'https://cdn.biztoc.com/e0e56e6a6c714085...,"Wed, 26 Mar 2025 16:15:45 GMT",Housebuilding plans forecast to boost economy ...,https://www.bbc.com/news/articles/cy4vj7yk0nyo...,"[The Office for Budget Responsibility, OBR]"
4,While the Spring Statement focusses on the wid...,{'s': 'https://cdn.biztoc.com/4e8e6b59bd0760f9...,"Wed, 26 Mar 2025 14:42:13 GMT",Three ways the Spring Statement could affect y...,https://www.bbc.com/news/articles/cvged1en8jro...,[Spring Statement]
5,UK growth forecast halved for this year\nThe U...,{'s': 'https://cdn.biztoc.com/45d65104d0616e5b...,"Wed, 26 Mar 2025 13:11:05 GMT",UK growth forecast halved for this year,https://www.bbc.com/news/articles/cqjd5rklyrko...,"[the Office for Budget Responsibility, OBR]"
6,Maeve Bradley took action against Citibank aft...,{'s': 'https://cdn.biztoc.com/4f1e70199b1315c3...,"Wed, 26 Mar 2025 00:24:14 GMT",Maternity discrimination case settled for £215k,https://www.bbc.com/news/articles/cvgp0j3jjnmo...,[Citibank]
7,Inflation falls to 2.8% ahead of Spring Statem...,{'s': 'https://cdn.biztoc.com/28f5d43595442dd9...,"Wed, 26 Mar 2025 07:17:32 GMT",Inflation falls to 2.8% ahead of Spring Statement,https://www.bbc.com/news/articles/cx2g3wwk01vo...,[Spring Statement\nUK]
9,CMA concerned that Ticketmaster may have breac...,{'s': 'https://cdn.biztoc.com/73e1932181f49674...,"Tue, 25 Mar 2025 13:29:03 GMT",Oasis sale 'may have misled fans' says watchdog,https://www.bbc.com/news/articles/cddy85n57j8o...,[CMA]
11,Lower Thames Crossing approved by government\n...,{'s': 'https://cdn.biztoc.com/64952168afdc8443...,"Tue, 25 Mar 2025 10:41:08 GMT",Lower Thames Crossing approved by government,https://www.bbc.com/news/articles/crewy5472gxo...,"[Lower Thames Crossing, The Lower Thames Cross..."
13,'I could lose £100K despite Woodford redress s...,{'s': 'https://cdn.biztoc.com/29997895f5f9c92c...,"Tue, 25 Mar 2025 00:49:47 GMT",'I could lose £100K despite Woodford redress s...,https://www.bbc.com/news/articles/cx2gw5y8er7o...,"[Woodford, Woodford]"
15,Hyundai unveils $21bn US expansion as Trump ta...,{'s': 'https://cdn.biztoc.com/483f0f0f4595aaef...,"Tue, 25 Mar 2025 04:52:13 GMT",Hyundai unveils $21bn US expansion as Trump ta...,https://www.bbc.com/news/articles/cgkmvdz144vo...,"[Hyundai, Trump, Hyundai, Hyundai]"
16,Chinese electric carmaker BYD sales beat Tesla...,{'s': 'https://cdn.biztoc.com/c5bcccf298f20868...,"Tue, 25 Mar 2025 03:24:09 GMT",Chinese electric carmaker BYD sales beat Tesla,https://www.bbc.com/news/articles/cd65d583qvzo...,"[BYD, BYD]"
17,You've requested a page on a website (www.bbc....,{'s': 'https://cdn.biztoc.com/43187929f577ea4f...,"Tue, 25 Mar 2025 00:06:48 GMT",Bitcoin in the bush - the crypto mine in remot...,https://www.bbc.co.ukundefined/?ref=biztoc.com,"[Cloudflare, Cloudflare]"
18,Pizza Hut workers accuse franchisee of docking...,{'s': 'https://cdn.biztoc.com/1ca0528ce353f00d...,"Tue, 25 Mar 2025 00:02:01 GMT",Pizza Hut workers accuse franchisee of docking...,https://www.bbc.com/news/articles/c3w10qnnjvyo...,"[Pizza Hut, Pizza Hut, Glenshire Group, Pizza ..."
21,Faisal Islam: No tax rises and no return to au...,{'s': 'https://cdn.biztoc.com/57ebb7f3a292730c...,"Mon, 24 Mar 2025 16:19:53 GMT",Faisal Islam: No tax rises and no return to au...,https://www.bbc.com/news/articles/c1kjxkkn3mzo...,"[Budget, Treasury]"
23,Morrisons to shut 52 cafes and 17 stores\nSupe...,{'s': 'https://cdn.biztoc.com/3bfff465ea9f7e4f...,"Mon, 24 Mar 2025 12:54:48 GMT",Morrisons to shut 52 cafes and 17 stores,https://www.bbc.com/news/articles/cqx0v5xprz4o...,[Supermarket]
24,Reeves confirms 15% cut to Civil Service runni...,{'s': 'https://cdn.biztoc.com/89f422fe424dc374...,"Sun, 23 Mar 2025 11:33:31 GMT",Reeves confirms 15% cut to Civil Service runni...,https://www.bbc.com/news/articles/cy5nzy403l0o...,"[Civil Service, BBC]"
26,National Grid confirms Heathrow never lost acc...,{'s': 'https://cdn.biztoc.com/915211d68dce4029...,"Mon, 24 Mar 2025 03:51:35 GMT",National Grid confirms Heathrow never lost acc...,https://www.bbc.com/news/articles/cdjy4m0n1exo...,"[the National Grid, the Financial Times]"
27,Disney's Snow White film tops box office despi...,{'s': 'https://cdn.biztoc.com/1feeec981f1229c1...,"Mon, 24 Mar 2025 02:58:23 GMT",Disney's Snow White film tops box office despi...,https://www.bbc.com/news/articles/c74ke77v7rvo...,"[Disney, Disney]"
30,UK mulls big tech tax changes to avoid US tari...,{'s': 'https://cdn.biztoc.com/b42d2cb30b8a8d56...,"Sun, 23 Mar 2025 12:02:08 GMT",UK mulls big tech tax changes to avoid US tariffs,https://www.bbc.com/news/articles/c8j0dgym8w1o...,"[Digital Services Tax, DST]"
32,In an interview with the BBC's Laura Kuenssber...,{'s': 'https://cdn.biztoc.com/54ca418fc26c24c2...,"Sat, 22 Mar 2025 05:46:59 GMT",Rachel Reeves: I will not 'tax and spend',https://www.bbc.com/news/articles/c78eg7dp9ypo...,[BBC]
36,Broadcasters fined £4m for freelance pay collu...,{'s': 'https://cdn.biztoc.com/ce6905775d598374...,"Fri, 21 Mar 2025 10:45:58 GMT",Broadcasters fined £4m for freelance pay collu...,https://www.bbc.com/news/articles/ce34q1792d0o...,"[BBC, IMG, ITV]"
39,Heathrow Airport closes all day over power out...,{'s': 'https://cdn.biztoc.com/391b66f483d1b895...,"Fri, 21 Mar 2025 03:32:18 GMT",Heathrow Airport closes all day over power outage,https://www.bbc.com/news/articles/cvg5dg4p2l0o...,[Heathrow]
40,Trump uses emergency powers to boost mineral p...,{'s': 'https://cdn.biztoc.com/6c8f847943ea1938...,"Fri, 21 Mar 2025 03:29:37 GMT",Trump uses emergency powers to boost mineral p...,https://www.bbc.com/news/articles/cwye089j1zdo...,[Trump]
43,TikTokers call for 'chubby filter' to be banne...,{'s': 'https://cdn.biztoc.com/bfbf4692cfa0b907...,"Fri, 21 Mar 2025 00:02:37 GMT",TikTokers call for 'chubby filter' to be banned,https://www.bbc.com/news/articles/c4gmvjvv6vjo...,"[TikTokers, TikTok, BBC]"
46,Tesla makes largest ever Cybertruck recall\nTh...,{'s': 'https://cdn.biztoc.com/58460be1ca706ec3...,"Thu, 20 Mar 2025 18:47:55 GMT",Tesla makes largest ever Cybertruck recall,https://www.bbc.com/news/articles/c0kgy20x0x4o...,"[Tesla, Tesla Cybertrucks]"
47,Family sues Boeing over whistleblower death\nT...,{'s': 'https://cdn.biztoc.com/cbab1c886f7607f0...,"Thu, 20 Mar 2025 16:24:49 GMT",Family sues Boeing over whistleblower death,https://www.bbc.com/news/articles/cwyje8e8rdlo...,"[Boeing, Boeing]"
48,EU delays plans to retaliate against Trump tar...,{'s': 'https://cdn.biztoc.com/1ef719daee2a2290...,"Thu, 20 Mar 2025 16:10:19 GMT",EU delays plans to retaliate against Trump tar...,https://www.bbc.com/news/articles/c62z157jvd8o...,"[EU, Trump, The European Union, EU]"
50,You're hired: Lord Sugar signs up to stay on T...,{'s': 'https://cdn.biztoc.com/607b8be6e9bbb280...,"Thu, 20 Mar 2025 01:45:51 GMT",You're hired: Lord Sugar signs up to stay on T...,https://www.bbc.com/news/articles/c20d8jlnkk8o...,"[Apprentice, BBC, Apprentice]"
51,The company is still valued at more than 100 t...,{'s': 'https://cdn.biztoc.com/7c9fe0a9425bcf84...,"Thu, 20 Mar 2025 00:05:40 GMT",Tesla's challenges run deeper than 'toxic' con...,https://www.bbc.com/news/articles/cz61vwjel2zo...,None
52,Bank of England expected to hold interest rate...,{'s': 'https://cdn.biztoc.com/44d44f3973cf5206...,"Thu, 20 Mar 2025 00:06:51 GMT",Bank of England expected to hold interest rate...,https://www.bbc.com/news/articles/ckgz82838l8o...,"[Bank of England, The Bank of England, Bank]"
55,US holds rates steady despite economy fears\nT...,{'s': 'https://cdn.biztoc.com/363289c0ff0ffe3f...,"Wed, 19 Mar 2025 18:35:30 GMT",US holds rates steady despite economy fears,https://www.bbc.com/news/articles/cvgp574lvdxo...,[the Federal Reserve's]
57,"Interest rates, set by the Bank of England, af...",{'s': 'https://cdn.biztoc.com/f6c4b4b6a65f0132...,"Wed, 19 Mar 2025 11:46:19 GMT",When will interest rates go down again?,https://www.bbc.co.uk/news/business-57764601?r...,[the Bank of England]
58,Ben & Jerry's says its boss ousted by Unilever...,{'s': 'https://cdn.biztoc.com/d7c4e44caebc9e2a...,"Wed, 19 Mar 2025 08:53:50 GMT",Ben & Jerry's says its boss ousted by Unilever,https://www.bbc.com/news/articles/ckg8pk9rpx4o...,"[Ben & Jerry's, Unilever\nBen & Jerry's, Unile..."

## **Preparing Text for NLP**

In [103]:
def NLP_Ready_Title(df):
  df["New_Title"] = (
        df["title"]
        .str.casefold()  # Converts to lowercase and handles Unicode better
        .str.replace(r"https?://\S+", "", regex=True)  # Remove URLs
        .str.replace(r"<a[^>]*>(.*?)</a>", r"\1", regex=True)  # Remove anchor tags but keep text
        .str.replace(r"<.*?>", " ", regex=True)  # Remove all HTML tags
        .str.replace(r"\s+", " ", regex=True)  # Replace multiple spaces with a single space
        .str.strip()  # Trim leading/trailing spaces
    )

  return df



def NLP_Ready_Body(df):
  df["New_Body"] = (
        df["body"]
        .str.casefold()  # Converts to lowercase and handles Unicode better
        .str.replace(r"https?://\S+", "", regex=True)  # Remove URLs
        .str.replace(r"<a[^>]*>(.*?)</a>", r"\1", regex=True)  # Remove anchor tags but keep text
        .str.replace(r"<.*?>", " ", regex=True)  # Remove all HTML tags
        .str.replace(r"\s+", " ", regex=True)  # Replace multiple spaces with a single space
        .str.strip()  # Trim leading/trailing spaces
    )

  return df

## **Applying NLP**

##### **TextBlob Method**

In [104]:
from textblob import TextBlob


def classify_sentiment(text):
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity
    if polarity > 0:
        return "Positive 😊"
    elif polarity < 0:
        return "Negative 😠"
    else:
        return "Neutral 😐"

In [105]:
NLP_Ready_Title(df)
NLP_Ready_Body(df)

<ipython-input-103-da07ed688a3a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["New_Title"] = (
<ipython-input-103-da07ed688a3a>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["New_Body"] = (

,body,img,published,title,url,companies_mentioned,New_Title,New_Body
0,Farage and NatWest settle dispute over bank ac...,{'s': 'https://cdn.biztoc.com/058954c045492a73...,"Wed, 26 Mar 2025 19:19:52 GMT",Farage and NatWest settle dispute over bank ac...,https://www.bbc.com/news/articles/czx79161e2wo...,"[NatWest, NatWest, Reform]",farage and natwest settle dispute over bank ac...,farage and natwest settle dispute over bank ac...
2,Housebuilding plans forecast to boost economy ...,{'s': 'https://cdn.biztoc.com/e0e56e6a6c714085...,"Wed, 26 Mar 2025 16:15:45 GMT",Housebuilding plans forecast to boost economy ...,https://www.bbc.com/news/articles/cy4vj7yk0nyo...,"[The Office for Budget Responsibility, OBR]",housebuilding plans forecast to boost economy ...,housebuilding plans forecast to boost economy ...
4,While the Spring Statement focusses on the wid...,{'s': 'https://cdn.biztoc.com/4e8e6b59bd0760f9...,"Wed, 26 Mar 2025 14:42:13 GMT",Three ways the Spring Statement could affect y...,https://www.bbc.com/news/articles/cvged1en8jro...,[Spring Statement],three ways the spring statement could affect y...,while the spring statement focusses on the wid...
5,UK growth forecast halved for this year\nThe U...,{'s': 'https://cdn.biztoc.com/45d65104d0616e5b...,"Wed, 26 Mar 2025 13:11:05 GMT",UK growth forecast halved for this year,https://www.bbc.com/news/articles/cqjd5rklyrko...,"[the Office for Budget Responsibility, OBR]",uk growth forecast halved for this year,uk growth forecast halved for this year the uk...
6,Maeve Bradley took action against Citibank aft...,{'s': 'https://cdn.biztoc.com/4f1e70199b1315c3...,"Wed, 26 Mar 2025 00:24:14 GMT",Maternity discrimination case settled for £215k,https://www.bbc.com/news/articles/cvgp0j3jjnmo...,[Citibank],maternity discrimination case settled for £215k,maeve bradley took action against citibank aft...
7,Inflation falls to 2.8% ahead of Spring Statem...,{'s': 'https://cdn.biztoc.com/28f5d43595442dd9...,"Wed, 26 Mar 2025 07:17:32 GMT",Inflation falls to 2.8% ahead of Spring Statement,https://www.bbc.com/news/articles/cx2g3wwk01vo...,[Spring Statement\nUK],inflation falls to 2.8% ahead of spring statement,inflation falls to 2.8% ahead of spring statem...
9,CMA concerned that Ticketmaster may have breac...,{'s': 'https://cdn.biztoc.com/73e1932181f49674...,"Tue, 25 Mar 2025 13:29:03 GMT",Oasis sale 'may have misled fans' says watchdog,https://www.bbc.com/news/articles/cddy85n57j8o...,[CMA],oasis sale 'may have misled fans' says watchdog,cma concerned that ticketmaster may have breac...
11,Lower Thames Crossing approved by government\n...,{'s': 'https://cdn.biztoc.com/64952168afdc8443...,"Tue, 25 Mar 2025 10:41:08 GMT",Lower Thames Crossing approved by government,https://www.bbc.com/news/articles/crewy5472gxo...,"[Lower Thames Crossing, The Lower Thames Cross...",lower thames crossing approved by government,lower thames crossing approved by government t...
13,'I could lose £100K despite Woodford redress s...,{'s': 'https://cdn.biztoc.com/29997895f5f9c92c...,"Tue, 25 Mar 2025 00:49:47 GMT",'I could lose £100K despite Woodford redress s...,https://www.bbc.com/news/articles/cx2gw5y8er7o...,"[Woodford, Woodford]",'i could lose £100k despite woodford redress s...,'i could lose £100k despite woodford redress s...
15,Hyundai unveils $21bn US expansion as Trump ta...,{'s': 'https://cdn.biztoc.com/483f0f0f4595aaef...,"Tue, 25 Mar 2025 04:52:13 GMT",Hyundai unveils $21bn US expansion as Trump ta...,https://www.bbc.com/news/articles/cgkmvdz144vo...,"[Hyundai, Trump, Hyundai, Hyundai]",hyundai unveils $21bn us expansion as trump ta...,hyundai unveils $21bn us expansion as trump ta...
16,Chinese electric carmaker BYD sales beat Tesla...,{'s': 'https://cdn.biztoc.com/c5bcccf298f20868...,"Tue, 25 Mar 2025 03:24:09 GMT",Chinese electric carmaker BYD sales beat Tesla,https://www.bbc.com/news/articles/cd65d583qvzo...,"[BYD, BYD]",chinese electric carmaker byd sales beat tesla,chinese electric carmaker byd sales beat tesla...
17,You've requested a page on a website (www.bbc....,{'s': 'https://cdn.biztoc.com/43187929f577ea4f...,"Tue, 25 Mar 2025 00:06:48 GMT",Bitcoin in the bush - the crypto mine in remot...,https://www.bbc.co.ukundefined/?ref=biztoc.com,"[Cloudflare, Cloudflare]",bitcoin in the bush - the crypto mine in remot...,you've requested a page on a website (www.bbc....
18,Pizza Hut workers accuse franchisee of docking...,{'s': 'https://cdn.biztoc.com/1ca0528ce353f00d...,"Tue, 25 Mar 2025 00:02:01 GMT",Pizza Hut workers accuse franchisee of docking...,https://www.bbc.com/news/articles/c3w10qnnjvyo...,"[Pizza Hut, Pizza Hut, Glenshire Group, Pizza ...",pizza hut workers accuse franchisee of docking...,pizza hut workers accuse franchisee of docking...
21,Faisal Islam: No tax rises and no return to au...,{'s': 'https://cdn.biztoc.com/57ebb7f3a292730c...,"Mon, 24 Mar 2025 16:19:53 GMT",Faisal Islam: No tax rises and no return to au...,https://www.bbc.com/news/articles/c1kjxkkn3mzo...,"[Budget, Treasury]",faisal islam: no tax rises and no return to au...,faisal islam: no tax rises and no return to au...
23,Morrisons to shut 52 cafes and 17 stores\nSupe...,{'s': 'https://cdn.biztoc.com/3bfff465ea9f7e4f...,"Mon, 24 Mar 2025 12:54:48 GMT",Morrisons to shut 52 cafes and 17 stores,https://www.bbc.com/news/articles/cqx0v5xprz4o...,[Supermarket],morrisons to shut 52 cafes and 17 stores,morrisons to shut 52 cafes and 17 stores super...
24,Reeves confirms 15% cut to Civil Service runni...,{'s': 'https://cdn.biztoc.com/89f422fe424dc374...,"Sun, 23 Mar 2025 11:33:31 GMT",Reeves confirms 15% cut to Civil Service runni...,https://www.bbc.com/news/articles/cy5nzy403l0o...,"[Civil Service, BBC]",reeves confirms 15% cut to civil service runni...,reeves confirms 15% cut to civil service runni...
26,National Grid confirms Heathrow never lost acc...,{'s': 'https://cdn.biztoc.com/915211d68dce4029...,"Mon, 24 Mar 2025 03:51:35 GMT",National Grid confirms Heathrow never lost acc...,https://www.bbc.com/news/articles/cdjy4m0n1exo...,"[the National Grid, the Financial Times]",national grid confirms heathrow never lost acc...,national grid confirms heathrow never lost acc...
27,Disney's Snow White film tops box office despi...,{'s': 'https://cdn.biztoc.com/1feeec981f1229c1...,"Mon, 24 Mar 2025 02:58:23 GMT",Disney's Snow White film tops box office despi...,https://www.bbc.com/news/articles/c74ke77v7rvo...,"[Disney, Disney]",disney's snow white film tops box office despi...,disney's snow white film tops box office despi...
30,UK mulls big tech tax changes to avoid US tari...,{'s': 'https://cdn.biztoc.com/b42d2cb30b8a8d56...,"Sun, 23 Mar 2025 12:02:08 GMT",UK mulls big tech tax changes to avoid US tariffs,https://www.bbc.com/news/articles/c8j0dgym8w1o...,"[Digital Services Tax, DST]",uk mulls big tech tax changes to avoid us tariffs,uk mulls big tech tax changes to avoid us tari...
32,In an interview with the BBC's Laura Kuenssber...,{'s': 'https://cdn.biztoc.com/54ca418fc26c24c2...,"Sat, 22 Mar 2025 05:46:59 GMT",Rachel Reeves: I will not 'tax and spend',https://www.bbc.com/news/articles/c78eg7dp9ypo...,[BBC],rachel reeves: i will not 'tax and spend',in an interview with the bbc's laura kuenssber...
36,Broadcasters fined £4m for freelance pay collu...,{'s': 'https://cdn.biztoc.com/ce6905775d598374...,"Fri, 21 Mar 2025 10:45:58 GMT",Broadcasters fined £4m for freelance pay collu...,https://www.bbc.com/news/articles/ce34q1792d0o...,"[BBC, IMG, ITV]",broadcasters fined £4m for freelance pay collu...,broadcasters fined £4m for freelance pay collu...
39,Heathrow Airport closes all day over power out...,{'s': 'https://cdn.biztoc.com/391b66f483d1b895...,"Fri, 21 Mar 2025 03:32:18 GMT",Heathrow Airport closes all day over power outage,https://www.bbc.com/news/articles/cvg5dg4p2l0o...,[Heathrow],heathrow airport closes all day over power outage,heathrow airport closes all day over power out...
40,Trump uses emergency powers to boost mineral p...,{'s': 'https://cdn.biztoc.com/6c8f847943ea1938...,"Fri, 21 Mar 2025 03:29:37 GMT",Trump uses emergency powers to boost mineral p...,https://www.bbc.com/news/articles/cwye089j1zdo...,[Trump],trump uses emergency powers to boost mineral p...,trump uses emergency powers to boost mineral p...
43,TikTokers call for 'chubby filter' to be banne...,{'s': 'https://cdn.biztoc.com/bfbf4692cfa0b907...,"Fri, 21 Mar 2025 00:02:37 GMT",TikTokers call for 'chubby filter' to be banned,https://www.bbc.com/news/articles/c4gmvjvv6vjo...,"[TikTokers, TikTok, BBC]",tiktokers call for 'chubby filter' to be banned,tiktokers call for 'chubby filter' to be banne...
46,Tesla makes largest ever Cybertruck recall\nTh...,{'s': 'https://cdn.biztoc.com/58460be1ca706ec3...,"Thu, 20 Mar 2025 18:47:55 GMT",Tesla makes largest ever Cybertruck recall,https://www.bbc.com/news/articles/c0kgy20x0x4o...,"[Tesla, Tesla Cybertrucks]",tesla makes largest ever cybertruck recall,tesla makes largest ever cybertruck recall tho...
47,Family sues Boeing over whistleblower death\nT...,{'s': 'https://cdn.biztoc.com/cbab1c886f7607f0...,"Thu, 20 Mar 2025 16:24:49 GMT",Family sues Boeing over whistleblower death,https://www.bbc.com/news/articles/cwyje8e8rdlo...,"[Boeing, Boeing]",family sues boeing over whistleblower death,family sues boeing over whistleblower death th...
48,EU delays plans to retaliate against Trump tar...,{'s': 'https://cdn.biztoc.com/1ef719daee2a2290...,"Thu, 20 Mar 2025 16:10:19 GMT",EU delays plans to retaliate against Trump tar...,https://www.bbc.com/news/articles/c62z157jvd8o...,"[EU, Trump, The European Union, EU]",eu delays plans to retaliate against trump tar...,eu delays plans to retaliate against trump tar...
50,You're hired: Lord Sugar signs up to stay on T...,{'s': 'https://cdn.biztoc.com/607b8be6e9bbb280...,"Thu, 20 Mar 2025 01:45:51 GMT",You're hired: Lord Sugar signs up to stay on T...,https://www.bbc.com/news/articles/c20d8jlnkk8o...,"[Apprentice, BBC, Apprentice]",you're hired: lord sugar signs up to stay on t...,you're hired: lord sugar signs up to stay on t...
51,The company is still valued at more than 100 t...,{'s': 'https://cdn.biztoc.com/7c9fe0a9425bcf84...,"Thu, 20 Mar 2025 00:05:40 GMT",Tesla's challenges run deeper than 'toxic' con...,https://www.bbc.com/news/articles/cz61vwjel2zo...,None,tesla's challenges run deeper than 'toxic' con...,the company is still valued at more than 100 t...
52,Bank of England expected to hold interest rate...,{'s': 'https://cdn.biztoc.com/44d44f3973cf5206...,"Thu, 20 Mar 2025 00:06:51 GMT",Bank of England expected to hold interest rate...,https://www.bbc.com/news/articles/ckgz82838l8o...,"[Bank of England, The Bank of England, Bank]",bank of england expected to hold interest rate...,bank of england expected to hold interest rate...
55,US holds rates steady despite economy fears\nT...,{'s': 'https://cdn.biztoc.com/363289c0ff0ffe3f...,"Wed, 19 Mar 2025 18:35:30 GMT",US holds rates steady despite economy fears,https://www.bbc.com/news/articles/cvgp574lvdxo...,[the Federal Reserve's],us holds rates steady despite economy fears,us holds rates steady despite economy fears th...
57,"Interest rates, set by the Bank of England, af...",{'s': 'https://cdn.biztoc.com/f6c4b4b6a65f0132...,"Wed, 19 Mar 2025 11:46:19 GMT",When will interest rates go down again?,https://www.bbc.co.uk/news/business-57764601?r...,[the Bank of England],when will interest rates go down again?,"interest rates, set by the bank of england, af..."
58,Ben & Jerry's says its boss ousted by Unilever...,{'s': 'https://cdn.biztoc.com/d7c4e44caebc9e2a...,"Wed, 19 Mar 2025 08:53:50 GMT",Ben & Jerry's says its boss ousted by Unilever,https://www.bbc.com/news/articles/ckg8pk9rpx4o...,"[Ben & Jerry's, Unilever\nBen & Jerry's, Unile...",ben & jerry's says its boss ousted by unilever,ben & jerry's says its boss ousted by unilever...

In [106]:
for title in df["New_Title"]:
  print(classify_sentiment(title))

Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Negative 😠
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Negative 😠
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Neutral 😐
Negative 😠
Positive 😊
Negative 😠
Neutral 😐

In [107]:
for body in df["New_Body"]:
  print(classify_sentiment(body))

Neutral 😐
Positive 😊
Neutral 😐
Positive 😊
Positive 😊
Positive 😊
Neutral 😐
Neutral 😐
Negative 😠
Positive 😊
Positive 😊
Negative 😠
Negative 😠
Negative 😠
Positive 😊
Neutral 😐
Positive 😊
Negative 😠
Neutral 😐
Neutral 😐
Neutral 😐
Positive 😊
Negative 😠
Negative 😠
Positive 😊
Positive 😊
Neutral 😐
Positive 😊
Positive 😊
Positive 😊
Positive 😊
Neutral 😐
Positive 😊

In [108]:
for title, body, companies in zip(df['New_Title'], df["New_Body"], df["companies_mentioned"]):
  if (classify_sentiment(title) == "Neutral 😐" and classify_sentiment(body) == "Positive 😊") or (classify_sentiment(title) == "Positive 😊" and classify_sentiment(body) == "Neutral 😐"):
    print(f"These companies might be worth looking at {companies}")

These companies might be worth looking at ['The Office for Budget Responsibility', 'OBR']
These companies might be worth looking at ['the Office for Budget Responsibility', 'OBR']
These companies might be worth looking at ['Citibank']
These companies might be worth looking at ['Spring Statement\nUK']
These companies might be worth looking at ['Hyundai', 'Trump', 'Hyundai', 'Hyundai']
These companies might be worth looking at ['BYD', 'BYD']
These companies might be worth looking at ['Supermarket']
These companies might be worth looking at ['the National Grid', 'the Financial Times']
These companies might be worth looking at ['Heathrow']
These companies might be worth looking at ['Tesla', 'Tesla Cybertrucks']
These companies might be worth looking at ['Boeing', 'Boeing']
These companies might be worth looking at ['Apprentice', 'BBC', 'Apprentice']
These companies might be worth looking at None
These companies might be worth looking at ["Ben & Jerry's", "Unilever\nBen & Jerry's", 'Unilever', 'Ben &']

##### **BERT (Transformers) Method**

In [111]:
from transformers import pipeline

# Load sentiment analysis pipeline
sentiment_pipeline = pipeline("sentiment-analysis")

# Iterate through the 'New_Title' column and analyze sentiment
for title in df["New_Title"]:
    sentiment = sentiment_pipeline(title)
    label = sentiment[0]['label']  # 'LABEL_0' for Negative, 'LABEL_1' for Positive
    print(f"Title: '{title}' -> Sentiment: {label}")


print()
print()


for body in df["New_Body"]:
    sentiment = sentiment_pipeline(title)
    label = sentiment[0]['label']  # 'LABEL_0' for Negative, 'LABEL_1' for Positive
    print(f"body: '{body}' -> Sentiment: {label}")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu

Title: 'farage and natwest settle dispute over bank account closure' -> Sentiment: NEGATIVE
Title: 'housebuilding plans forecast to boost economy by £6.8bn' -> Sentiment: POSITIVE
Title: 'three ways the spring statement could affect you and your money' -> Sentiment: NEGATIVE
Title: 'uk growth forecast halved for this year' -> Sentiment: NEGATIVE
Title: 'maternity discrimination case settled for £215k' -> Sentiment: NEGATIVE
Title: 'inflation falls to 2.8% ahead of spring statement' -> Sentiment: NEGATIVE
Title: 'oasis sale 'may have misled fans' says watchdog' -> Sentiment: NEGATIVE
Title: 'lower thames crossing approved by government' -> Sentiment: POSITIVE
Title: ''i could lose £100k despite woodford redress scheme'' -> Sentiment: NEGATIVE
Title: 'hyundai unveils $21bn us expansion as trump tariffs loom' -> Sentiment: NEGATIVE
Title: 'chinese electric carmaker byd sales beat tesla' -> Sentiment: POSITIVE
Title: 'bitcoin in the bush - the crypto mine in remote zambia' -> Sentiment: NEGATIVE
Title: 'pizza hut workers accuse franchisee of docking wages' -> Sentiment: NEGATIVE
Title: 'faisal islam: no tax rises and no return to austerity but will it last?' -> Sentiment: NEGATIVE
Title: 'morrisons to shut 52 cafes and 17 stores' -> Sentiment: NEGATIVE
Title: 'reeves confirms 15% cut to civil service running costs' -> Sentiment: POSITIVE
Title: 'national grid confirms heathrow never lost access to power' -> Sentiment: POSITIVE
Title: 'disney's snow white film tops box office despite bad reviews' -> Sentiment: POSITIVE
Title: 'uk mulls big tech tax changes to avoid us tariffs' -> Sentiment: NEGATIVE
Title: 'rachel reeves: i will not 'tax and spend'' -> Sentiment: POSITIVE
Title: 'broadcasters fined £4m for freelance pay collusion' -> Sentiment: NEGATIVE
Title: 'heathrow airport closes all day over power outage' -> Sentiment: NEGATIVE
Title: 'trump uses emergency powers to boost mineral production' -> Sentiment: POSITIVE
Title: 'tiktokers call for 'chubby filter' to be banned' -> Sentiment: NEGATIVE
Title: 'tesla makes largest ever cybertruck recall' -> Sentiment: POSITIVE
Title: 'family sues boeing over whistleblower death' -> Sentiment: NEGATIVE
Title: 'eu delays plans to retaliate against trump tariffs' -> Sentiment: NEGATIVE
Title: 'you're hired: lord sugar signs up to stay on the apprentice into his 80s' -> Sentiment: POSITIVE
Title: 'tesla's challenges run deeper than 'toxic' controversy around elon musk' -> Sentiment: POSITIVE
Title: 'bank of england expected to hold interest rates at 4.5%' -> Sentiment: NEGATIVE
Title: 'us holds rates steady despite economy fears' -> Sentiment: POSITIVE
Title: 'when will interest rates go down again?' -> Sentiment: NEGATIVE
Title: 'ben & jerry's says its boss ousted by unilever' -> Sentiment: NEGATIVE


body: 'farage and natwest settle dispute over bank account closure natwest and nigel farage have settled the dispute over the closure of one of his bank accounts. the agreed settlement comes almost two years after the reform uk leader had his account with coutts, the prestigious private bank for the…' -> Sentiment: NEGATIVE
body: 'housebuilding plans forecast to boost economy by £6.8bn housebuilding is forecast to hit a 40-year high, with reforms to the planning system expected to boost the economy by £6.8bn, according to the independent spending watchdog. the office for budget responsibility (obr) said changes including…' -> Sentiment: NEGATIVE
body: 'while the spring statement focusses on the wider uk economy, it could have implications for your money.' -> Sentiment: NEGATIVE
body: 'uk growth forecast halved for this year the uk economy is now predicted to grow at a much slower pace this year than previously expected, according to the government's official forecaster. presenting her spring statement, chancellor rachel reeves said the office for budget responsibility (obr)…' -> Sentiment: NEGATIVE
body: 'maeve bradley took action against citibank after it promoted the person who covered her maternity leave.' -> Sentiment: NEGATIVE
body: 'inflation falls to 2.8% ahead of spring statement uk inflation fell to 2.8% in the year to february, driven by changes to women's clothing prices. the figures come ahead of chancellor rachel reeves' spring statement, where she will set out her economic plans.' -> Sentiment: NEGATIVE
body: 'cma concerned that ticketmaster may have breached consumer protection law for oasis reunion tour.' -> Sentiment: NEGATIVE
body: 'lower thames crossing approved by government the largest road tunnel in the uk will be built after an £8.3bn plan was approved by the government. the lower thames crossing would link tilbury, essex, and gravesend in kent by two tunnels running underneath the river thames. national highways hoped…' -> Sentiment: NEGATIVE
body: ''i could lose £100k despite woodford redress scheme' people who lost tens of thousands of pounds when a star stockpicker's investment fund collapsed say they have been let down by the uk's financial regulator and are calling on mps to investigate. around 300,000 people lost money when woodford…' -> Sentiment: NEGATIVE
body: 'hyundai unveils $21bn us expansion as trump tariffs loom south korean carmaking giant hyundai has unveiled $21bn (£16.3bn) of investment in the us. the plan includes a new $5.8bn steel plant in the southern state of louisiana. hyundai also said it will expand its american vehicle production and…' -> Sentiment: NEGATIVE
body: 'chinese electric carmaker byd sales beat tesla chinese electric vehicle maker byd has reported annual revenue for 2024 that has leapfrogged rival tesla. the shenzhen-based firm says revenue rose by 29% to come in at 777 billion yuan ($107bn; £83bn), boosted by sales of its hybrid vehicles. this…' -> Sentiment: NEGATIVE
body: 'you've requested a page on a website (www.bbc.co.ukundefined) that is on the cloudflare network. cloudflare is currently unable to resolve your requested domain (www.bbc.co.ukundefined). if you are a visitor of this website: please try again in a few minutes. if you are the owner of this…' -> Sentiment: NEGATIVE
body: 'pizza hut workers accuse franchisee of docking wages pizza hut workers are accusing a franchise of ''blatantly unlawful'' behaviour alleging it has altered timesheets, docked wages and stopped payments per delivery. glenshire group which runs all 22 pizza hut delivery outlets in scotland has been…' -> Sentiment: NEGATIVE
body: 'faisal islam: no tax rises and no return to austerity but will it last? "definitely not a budget" is the basic message emerging from the treasury about wednesday's economic statement. there will not just be no red box outside number 11, there will only be a "thin book" of new policies with a…' -> Sentiment: NEGATIVE
body: 'morrisons to shut 52 cafes and 17 stores supermarket chain morrisons is to shut 52 cafes and 17 stores putting hundreds of jobs at risk. the retailer will also close a number of in-store services, like the meat and fish counters, pharmacies and its market kitchens at certain sites in an attempt to…' -> Sentiment: NEGATIVE
body: 'reeves confirms 15% cut to civil service running costs government running costs will be cut by 15% by the end of the decade, the chancellor has promised. rachel reeves told the bbc savings would be made from back office and administrative roles rather than front-line services. but unions warned…' -> Sentiment: NEGATIVE
body: 'national grid confirms heathrow never lost access to power the chief executive of the national grid has confirmed power was available to keep heathrow open throughout friday's shutdown. in an interview with the financial times, john pettigrew said the fire that knocked out a substation was a…' -> Sentiment: NEGATIVE
body: 'disney's snow white film tops box office despite bad reviews disney's live-action version of the classic fairy-tale snow white has topped the north american box office chart despite a slew of underwhelming reviews. the movie has taken an estimated $87.3m (£67.5m) globally during its opening…' -> Sentiment: NEGATIVE
body: 'uk mulls big tech tax changes to avoid us tariffs uk taxes on big tech firms may be changed as part of a deal to avoid us president donald trump's next raft of tariffs, chancellor rachel reeves has suggested. she said talks are "ongoing" about tweaks to the digital services tax (dst), which…' -> Sentiment: NEGATIVE
body: 'in an interview with the bbc's laura kuenssberg, the chancellor opened up on the public finances and how she's finding the job.' -> Sentiment: NEGATIVE
body: 'broadcasters fined £4m for freelance pay collusion four of the uk's biggest sports broadcast and production companies have been fined more than £4m for illegally colluding on freelance pay rates. the uk's competition regulator said the bbc, bt, img and itv must pay a combined £4.24m after being…' -> Sentiment: NEGATIVE
body: 'heathrow airport closes all day over power outage heathrow airport is closing all day friday because of a large fire at a nearby electrical substation that supplies it. the airport is experiencing a "significant power outage" because of the fire, a statement from heathrow said. "to maintain the…' -> Sentiment: NEGATIVE
body: 'trump uses emergency powers to boost mineral production us president donald trump has invoked emergency powers to expand domestic production of critical minerals as he tries to reduce us reliance on imports from countries like china. the executive order, which uses cold war era legislation,…' -> Sentiment: NEGATIVE
body: 'tiktokers call for 'chubby filter' to be banned tiktok users have told the bbc they think a viral tool which makes people appear overweight should be banned from the platform. known as a "chubby filter", the artificial intelligence (ai) tool takes a photo of a person and edits their appearance to…' -> Sentiment: NEGATIVE
body: 'tesla makes largest ever cybertruck recall thousands of tesla cybertrucks have been recalled in the us due to concerns about part of the electric car's trim falling off in the model's eighth and largest ever recall. the issue affects more than 46,000 trucks made in 2024 and 2025, which analysts…' -> Sentiment: NEGATIVE
body: 'family sues boeing over whistleblower death this story contains details of someone taking their own life, which some readers may find distressing. the family of a boeing whistleblower who took his own life last year has filed a wrongful death lawsuit against the company. the complaint alleges that…' -> Sentiment: NEGATIVE
body: 'eu delays plans to retaliate against trump tariffs the european union (eu) has delayed plans to hit back at us president donald trump's steel and aluminium tariffs until the middle of next month. the trading bloc was set to impose duties on us products, including a 50% levy on whiskey, from 1…' -> Sentiment: NEGATIVE
body: 'you're hired: lord sugar signs up to stay on the apprentice into his 80s lord sugar has signed a new three-year deal with the bbc to stay on the apprentice. the billionaire was already contracted to do the 20th series of the show next year, but says he has signed to do three more series, taking…' -> Sentiment: NEGATIVE
body: 'the company is still valued at more than 100 times its earnings - but it faces problems that experts say go beyond questions around its ceo' -> Sentiment: NEGATIVE
body: 'bank of england expected to hold interest rates at 4.5% the bank of england is expected to keep interest rates on hold when policymakers announce their latest decision on thursday. the bank rate heavily influences the cost of borrowing for households, businesses and the government, as well as…' -> Sentiment: NEGATIVE
body: 'us holds rates steady despite economy fears the us central bank has kept interest rates unchanged for the second time in a row, while warning that economic uncertainty had increased. the decision, which was widely expected, left the federal reserve's benchmark interest rate hovering around 4.3%,…' -> Sentiment: NEGATIVE
body: 'interest rates, set by the bank of england, affect mortgage, loan and savings rates for millions.' -> Sentiment: NEGATIVE
body: 'ben & jerry's says its boss ousted by unilever ben & jerry's has said its chief executive, david stever, was being removed by its parent company, unilever, in a growing dispute over the ice cream company's political activism. the allegation was part of a legal case filed in a us court by ben &…' -> Sentiment: NEGATIVE

In [115]:
for title, body, companies in zip(df['New_Title'], df["New_Body"], df["companies_mentioned"]):
    if (sentiment_pipeline(title)[0]["label"] == 'POSITIVE' and sentiment_pipeline(body)[0]["label"] == 'POSITIVE'):
        print(f"These companies might be worth looking at: {companies}")

These companies might be worth looking at: ['Lower Thames Crossing', 'The Lower Thames Crossing']
These companies might be worth looking at: ['BYD', 'BYD']
These companies might be worth looking at: ['the National Grid', 'the Financial Times']
These companies might be worth looking at: ['Disney', 'Disney']
These companies might be worth looking at: ['BBC']
These companies might be worth looking at: ['Trump']
These companies might be worth looking at: ['Apprentice', 'BBC', 'Apprentice']

##### **NLTK (SentiWordNet) Method**

In [118]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()

text = "The movie was quite interesting but had a slow start."
print(sia.polarity_scores(text))

{'neg': 0.0, 'neu': 0.8, 'pos': 0.2, 'compound': 0.2492}

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [119]:
for title in df["New_Title"]:
  print(sia.polarity_scores(title))

{'neg': 0.252, 'neu': 0.748, 'pos': 0.0, 'compound': -0.4019}
{'neg': 0.0, 'neu': 0.722, 'pos': 0.278, 'compound': 0.4019}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.698, 'pos': 0.302, 'compound': 0.3818}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.244, 'neu': 0.444, 'pos': 0.311, 'compound': 0.1531}
{'neg': 0.278, 'neu': 0.722, 'pos': 0.0, 'compound': -0.4019}
{'neg': 0.192, 'neu': 0.808, 'pos': 0.0, 'compound': -0.2263}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.205, 'neu': 0.795, 'pos': 0.0, 'compound': -0.2023}
{'neg': 0.211, 'neu': 0.789, 'pos': 0.0, 'compound': -0.296}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.208, 'neu': 0.792, 'pos': 0.0, 'compound': -0.2732}
{'neg': 0.0, 'neu': 0.803, 'pos': 0.197, 'compound': 0.2411}
{'neg': 0.0, 'neu': 0.565, 'pos': 0.435, 'compound': 0.7311}
{'neg': 0.196, 'neu': 0.804, 'pos': 0.0, 'compound': -0.296}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.163, 'neu': 0.581, 'pos': 0.256, 'compound': 0.2023}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.23, 'neu': 0.531, 'pos': 0.239, 'compound': 0.0258}
{'neg': 0.3, 'neu': 0.7, 'pos': 0.0, 'compound': -0.4588}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.438, 'neu': 0.562, 'pos': 0.0, 'compound': -0.5994}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'compound': 0.0772}
{'neg': 0.0, 'neu': 0.75, 'pos': 0.25, 'compound': 0.4588}
{'neg': 0.0, 'neu': 0.72, 'pos': 0.28, 'compound': 0.3252}
{'neg': 0.0, 'neu': 0.667, 'pos': 0.333, 'compound': 0.4588}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

In [120]:
for body in df["New_Body"]:
  print(sia.polarity_scores(body))

{'neg': 0.101, 'neu': 0.86, 'pos': 0.039, 'compound': -0.5106}
{'neg': 0.0, 'neu': 0.884, 'pos': 0.116, 'compound': 0.6597}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.943, 'pos': 0.057, 'compound': 0.3818}
{'neg': 0.067, 'neu': 0.778, 'pos': 0.156, 'compound': 0.3818}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.081, 'neu': 0.815, 'pos': 0.104, 'compound': 0.296}
{'neg': 0.179, 'neu': 0.821, 'pos': 0.0, 'compound': -0.8126}
{'neg': 0.039, 'neu': 0.915, 'pos': 0.047, 'compound': 0.1027}
{'neg': 0.0, 'neu': 0.949, 'pos': 0.051, 'compound': 0.3612}
{'neg': 0.0, 'neu': 0.891, 'pos': 0.109, 'compound': 0.5994}
{'neg': 0.116, 'neu': 0.884, 'pos': 0.0, 'compound': -0.5267}
{'neg': 0.103, 'neu': 0.773, 'pos': 0.124, 'compound': 0.296}
{'neg': 0.037, 'neu': 0.857, 'pos': 0.105, 'compound': 0.4215}
{'neg': 0.061, 'neu': 0.905, 'pos': 0.034, 'compound': -0.09}
{'neg': 0.05, 'neu': 0.91, 'pos': 0.041, 'compound': -0.1124}
{'neg': 0.0, 'neu': 0.872, 'pos': 0.128, 'compound': 0.7311}
{'neg': 0.081, 'neu': 0.919, 'pos': 0.0, 'compound': -0.5267}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.124, 'neu': 0.792, 'pos': 0.085, 'compound': -0.0}
{'neg': 0.101, 'neu': 0.861, 'pos': 0.038, 'compound': -0.4588}
{'neg': 0.2, 'neu': 0.668, 'pos': 0.132, 'compound': -0.5994}
{'neg': 0.156, 'neu': 0.788, 'pos': 0.057, 'compound': -0.6597}
{'neg': 0.032, 'neu': 0.968, 'pos': 0.0, 'compound': -0.1531}
{'neg': 0.263, 'neu': 0.737, 'pos': 0.0, 'compound': -0.9274}
{'neg': 0.077, 'neu': 0.923, 'pos': 0.0, 'compound': -0.4767}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.125, 'neu': 0.807, 'pos': 0.068, 'compound': -0.3818}
{'neg': 0.0, 'neu': 0.847, 'pos': 0.153, 'compound': 0.7964}
{'neg': 0.089, 'neu': 0.719, 'pos': 0.192, 'compound': 0.684}
{'neg': 0.0, 'neu': 0.833, 'pos': 0.167, 'compound': 0.4588}
{'neg': 0.052, 'neu': 0.886, 'pos': 0.062, 'compound': -0.128}

In [122]:
for title, body, companies in zip(df['New_Title'], df["New_Body"], df["companies_mentioned"]):
    title_scores = sia.polarity_scores(title)  # Get sentiment scores for title
    body_scores = sia.polarity_scores(body)  # Get sentiment scores for body

    if title_scores["pos"] > title_scores["neg"] and body_scores["pos"] > body_scores["neg"]:
        print(f"These companies might be worth looking at: {companies}")

These companies might be worth looking at: ['The Office for Budget Responsibility', 'OBR']
These companies might be worth looking at: ['the Office for Budget Responsibility', 'OBR']
These companies might be worth looking at: ['Lower Thames Crossing', 'The Lower Thames Crossing']
These companies might be worth looking at: ['Disney', 'Disney']
These companies might be worth looking at: ['Bank of England', 'The Bank of England', 'Bank']
These companies might be worth looking at: ["the Federal Reserve's"]
These companies might be worth looking at: ['the Bank of England']